# Script para generar SEO completo para TODAS las 180 calculadoras
# Genera whatIs y whyUse para cada calculadora

$calculadoras = @(
    @{slug='calculadora-porcentaje'; whatIs='Un porcentaje es una manera de expresar un número como parte de 100. Se utiliza el símbolo % para representarlo. Por ejemplo, el 25% significa 25 de cada 100 unidades. Nuestro calculador te permite obtener instantáneamente resultados precisos para cualquier cálculo de porcentajes sin necesidad de realizar operaciones manuales.'; whyUse='Los porcentajes están en todas partes: descuentos en compras, intereses bancarios, cambios de precio, probabilidades y muchísimo más. Ya sea que necesites calcular un descuento en la tienda, saber qué porcentaje representa una cantidad respecto a un total, o encontrar el valor original de un precio con descuento, esta herramienta te ahorra tiempo y evita errores de cálculo.'},
    @{slug='calculadora-hipoteca'; whatIs='Una hipoteca es un préstamo que solicitas al banco para comprar una vivienda. El banco te presta dinero y tú te comprometes a devolverlo en cuotas mensuales durante un período de tiempo (normalmente 20-30 años), pagando además intereses. Nuestra calculadora te muestra exactamente cuánto pagarás cada mes, el total de intereses y cómo se distribuye el dinero entre capital e intereses.'; whyUse='Comprender los detalles de tu hipoteca es fundamental antes de solicitarla. Saber cuál será la cuota mensual, cuánto pagarás en total y cómo cambian los intereses a lo largo del tiempo te ayuda a tomar una decisión financiera inteligente. Esta herramienta te permite simular diferentes escenarios: cambiar el plazo, la cantidad prestada o la tasa de interés.'},
    @{slug='calculadora-imc'; whatIs='El IMC (Índice de Masa Corporal) es una medida que relaciona tu peso con tu altura para evaluar si tienes un peso saludable. Se calcula dividiendo el peso en kilogramos entre la altura en metros al cuadrado. El resultado te ubica en categorías: peso insuficiente, peso normal, sobrepeso u obesidad. Es una herramienta simple de usar pero debe complementarse con evaluaciones médicas profesionales.'; whyUse='Conocer tu IMC es importante para mantener la salud. Te ayuda a identificar si tu peso actual es saludable para tu altura y edad. Muchas personas usan esta calculadora como punto de partida para cambios en su estilo de vida, dieta o rutina de ejercicio. Sin embargo, recuerda que el IMC es solo un indicador y no reemplaza el consejo médico profesional.'},
    @{slug='conversor-temperatura'; whatIs='La temperatura es una medida de cuán caliente o frío está algo. Existen tres escalas principales: Celsius (usado en la mayoría del mundo), Fahrenheit (usado principalmente en EE.UU.) y Kelvin (usado en ciencia). Convertir entre estas escalas es esencial en campos como la cocina, la química, la medicina y la meteorología. Nuestra herramienta realiza estas conversiones al instante.'; whyUse='Necesitas convertir temperaturas constantemente en la vida cotidiana: recetas que usan grados Fahrenheit, reportes de clima internacionales, investigaciones científicas o especificaciones técnicas. Esta calculadora elimina la necesidad de recordar fórmulas complicadas. Simplemente ingresa la temperatura y selecciona las unidades para obtener la conversión exacta en segundos.'},
    @{slug='conversor-longitud'; whatIs='La longitud es la medida de distancia entre dos puntos. Existen muchas unidades de medida: metros, kilómetros, pies, pulgadas, millas, centímetros y más. Cada país y profesión usa unidades diferentes, lo que hace necesario convertir constantemente entre ellas. Nuestro conversor te permite transformar cualquier medida de longitud de forma rápida y precisa.'; whyUse='Convertir unidades de longitud es necesario en muchas situaciones: leer planos de construcción, comprar materiales en tiendas internacionales, entender instrucciones técnicas, viajar a otros países o trabajar en campos como la ingeniería. Esta herramienta te ahorra tiempo en cálculos manuales y evita errores costosos.'},
    @{slug='conversor-peso'; whatIs='El peso es una medida de la masa de un objeto. Existen diferentes unidades según el país y la industria: kilogramos, gramos, libras, onzas, toneladas, entre otras. Mientras algunos países usan el sistema métrico, otros como EE.UU. utilizan el sistema imperial. Convertir entre estas unidades es esencial en comercio, cocina, medicina y logística.'; whyUse='Necesitas convertir pesos cuando compras productos internacionales, sigues recetas de otros países, interpretas especificaciones técnicas o trabajas en industrias que usan diferentes sistemas. Esta calculadora hace que las conversiones sean instantáneas y confiables, evitando errores que podrían ser costosos en contextos profesionales.'},
    @{slug='calculadora-descuento'; whatIs='Un descuento es una reducción del precio original de un producto o servicio, expresada generalmente como un porcentaje. Por ejemplo, un descuento del 20% reduce el precio en esa proporción. Entender cómo se aplican los descuentos es fundamental para hacer compras inteligentes y reconocer buenas ofertas. Nuestra herramienta te muestra exactamente cuánto ahorras con cada descuento.'; whyUse='Los descuentos están en todas partes: rebajas en tiendas, ofertas en línea, cupones, promociones estacionales y más. Necesitas saber rápidamente cuál es el precio final y cuánto dinero realmente ahorras. Esta calculadora elimina confusiones y te permite comparar ofertas de forma inteligente para tomar decisiones de compra más informadas.'},
    @{slug='calculadora-nomina'; whatIs='La nómina es el pago que recibes por tu trabajo. Está compuesta por el salario bruto (antes de impuestos) y el salario neto (después de deducir impuestos, seguridad social y otras retenciones). Entender tu nómina es crucial para saber realmente cuánto dinero recibirás y cómo se distribuyen tus ingresos entre impuestos y otras deducciones.'; whyUse='Necesitas calcular tu nómina para planificar tu presupuesto personal, entender tus impuestos, negociar mejor tu salario o verificar que tus cálculos sean correctos. Esta herramienta te muestra desglosadamente cómo se divide tu salario y cuáles son tus retenciones reales, ayudándote a tomar decisiones financieras más informadas.'},
    @{slug='calculadora-iva'; whatIs='El IVA (Impuesto sobre el Valor Añadido) es un impuesto que se aplica en la mayoría de los productos y servicios. El porcentaje varía según el país y el tipo de producto: en España hay tipos del 4%, 10% y 21%. Cuando ves un precio en una tienda, generalmente incluye el IVA. Es importante saber cómo extraerlo o calcularlo para entender realmente cuánto cuesta algo.'; whyUse='Necesitas calcular IVA si eres empresario, trabajas en contabilidad, eres autónomo o simplemente quieres saber el precio real de un producto sin impuestos. Esta herramienta te permite extraer el IVA de un precio final o añadirlo a un precio base en segundos, sin necesidad de hacer cálculos complicados manualmente.'},
    @{slug='nota-media'; whatIs='La nota media es el promedio de todas tus calificaciones. Se calcula sumando todas tus notas y dividiéndolas entre el número de calificaciones. En sistemas educativos más complejos, las notas se ponderan según los créditos (importancia) de cada asignatura. Saber tu nota media te ayuda a entender tu desempeño académico general y proyectar tu calificación final.'; whyUse='Necesitas calcular tu nota media para entender cómo vas académicamente, saber qué nota necesitas en exámenes futuros para alcanzar tu objetivo, o preparar solicitudes para universidades o becas que requieren promedios mínimos. Esta herramienta simplifica el cálculo especialmente cuando tienes muchas asignaturas con diferentes créditos o pesos.'},
    @{slug='consumo-electrico'; whatIs='El consumo eléctrico es la cantidad de energía que usan tus electrodomésticos. Se mide en kilovatios-hora (kWh). Cada aparato tiene una potencia (en vatios) y el tiempo que lo usas determina cuánta energía consume. Entender el consumo es importante para controlar tus gastos de electricidad y ser más eficiente energéticamente.'; whyUse='Quieres saber cuánto cuesta realmente usar cada electrodoméstico, identificar cuál consume más energía, reducir tu factura de electricidad o ser más consciente del impacto ambiental de tu consumo. Esta calculadora te muestra el costo detallado por aparato y permite simular cambios para ahorrar dinero.'},
    @{slug='velocidad-lectura'; whatIs='La velocidad de lectura es cuántas palabras puedes leer en un minuto, medida en palabras por minuto (PPM). Las personas tienen velocidades diferentes según su edad, entrenamiento y el tipo de texto. Una velocidad media está alrededor de 200-300 PPM, pero se puede entrenar para leer más rápido manteniendo la comprensión. Medir tu velocidad te ayuda a establecer metas de lectura.'; whyUse='Necesitas medir tu velocidad de lectura para establecer objetivos personales, entender cuánto tiempo tardará en completar un libro o documento, o identificar si necesitas entrenar tu velocidad lectora. Esta herramienta es especialmente útil para estudiantes, profesionales que leen mucho y personas interesadas en técnicas de lectura rápida.'},
    @{slug='consumo-combustible'; whatIs='El consumo de combustible es la cantidad de gasolina o diésel que usa tu vehículo. Se mide generalmente en litros por 100 km (L/100km) o millas por galón (MPG). El consumo varía según el tipo de vehículo, el estilo de conducción, el tráfico y las condiciones de la carretera. Conocer tu consumo es fundamental para controlar gastos y planificar viajes.'; whyUse='Necesitas calcular consumo de combustible para presupuestar tus gastos de gasolina, planificar viajes largos, comparar vehículos al comprar uno nuevo, o entender cuánto te cuesta realmente cada trayecto. Esta herramienta elimina la adivinanza y te permite tomar decisiones más informadas sobre tu transporte.'},
    @{slug='diferencia-horaria'; whatIs='La diferencia horaria es el intervalo de tiempo entre dos zonas horarias diferentes. El mundo se divide en 24 zonas horarias, cada una con una hora diferente. Cuando viajas a otro país o trabajas con personas en otros continentes, necesitas saber rápidamente qué hora es en el otro lugar para coordinar reuniones y actividades.'; whyUse='Necesitas calcular diferencias horarias si trabajas remotamente con equipos internacionales, planificas videoconferencias con gente en otros países, viajas frecuentemente, o simplemente quieres saber qué hora es en otra ciudad del mundo. Esta herramienta evita confusiones y permite coordinar actividades globales sin errores.'},
    @{slug='calculadora-propina'; whatIs='Una propina es una cantidad de dinero que das voluntariamente como agradecimiento por un servicio recibido. Las propinas son comunes en restaurantes, bares, taxis y otros servicios. El monto depende de la calidad del servicio y de las costumbres del país. Calcular la propina correcta puede ser complicado cuando pides en un restaurante concurrido o cuando vas con amigos.'; whyUse='Necesitas calcular propina rápidamente en un restaurante para no retrasar a otros clientes, dividir la propina equitativamente entre amigos, entender cuánto es un porcentaje justo en diferentes países, o simplemente no pensar en matemáticas mientras disfrutas tu comida. Esta herramienta resuelve estos cálculos al instante.'},
    @{slug='tiempo-estudio'; whatIs='El tiempo de estudio es cuántas horas necesitas dedicar a aprender un tema para prepararse adecuadamente. Depende de varios factores: la dificultad del tema, tu nivel de comprensión, la cantidad de material a aprender y el tiempo disponible. Planificar correctamente tu tiempo de estudio es fundamental para prepararte bien sin abrumar tu calendario.'; whyUse='Necesitas calcular tiempo de estudio para planificar tu preparación para exámenes, distribuir tus horas de estudio de forma eficiente, identificar si tienes suficiente tiempo para aprender todo, o ajustar tu plan de estudios. Esta herramienta te ayuda a ser realista sobre cuánto tiempo realmente necesitas dedicar.'},
    @{slug='calculadora-beca'; whatIs='Una beca es una ayuda económica que ofrecen instituciones educativas, gobiernos u organizaciones para que estudiantes puedan pagar sus estudios. Las becas pueden cubrir matrícula, libros, alojamiento y otros gastos. Para acceder a una beca generalmente tienes que cumplir requisitos académicos y económicos específicos.'; whyUse='Necesitas calcular si cumples los requisitos de una beca para solicitarla, entender cuánta ayuda recibirías, planificar tus finanzas educativas, o explorar diferentes opciones de becas disponibles. Esta herramienta te muestra rápidamente si eres elegible y cuánto dinero podrías ahorrar en tus estudios.'},
    @{slug='peso-equipaje'; whatIs='El peso de equipaje es cuánto pesan tus maletas y pertenencias cuando viajas. Las aerolíneas tienen límites de peso permitido para bagaje de mano y equipaje facturado. Exceder estos límites resulta en cargos adicionales costosos. Conocer el peso de tu equipaje antes de ir al aeropuerto evita sorpresas desagradables.'; whyUse='Necesitas pesar tu equipaje antes de viajar para evitar cargos por exceso de peso en el aeropuerto, asegurarte de que cumples con los límites de la aerolínea, distribuir el peso equitativamente entre maletas, o simplemente saber cuánto carga llevas. Esta herramienta te ayuda a planificar tu viaje sin sorpresas financieras.'},
    @{slug='coste-viaje'; whatIs='El coste de viaje es el gasto total que realizas en un viaje, incluyendo transporte, alojamiento, comidas, actividades y otros gastos. Calcular el coste total te ayuda a presupuestar correctamente, ahorrar dinero y entender cuánto gastaste después del viaje.'; whyUse='Necesitas calcular el coste de viaje para presupuestar antes de viajar, dividir gastos equitativamente con amigos o familia, entender tu gasto real de viaje, o planificar viajes futuros más realistas. Esta herramienta suma todos tus gastos y muestra desglose detallado por categoría.'},
    @{slug='huella-carbono'; whatIs='La huella de carbono es la cantidad total de dióxido de carbono (CO2) que emites directa o indirectamente a través de tus actividades. Incluye emisiones de transporte, consumo de energía en el hogar, alimentos que consumes y otros hábitos. Calcular tu huella de carbono es el primer paso para reducir tu impacto ambiental.'; whyUse='Necesitas entender tu impacto ambiental para tomar decisiones más conscientes, reducir tus emisiones de carbono, contribuir a la lucha contra el cambio climático, o cumplic con requisitos corporativos de sostenibilidad. Esta herramienta te muestra qué actividades generan más emisiones para que puedas enfocarte en cambios significativos.'},
    @{slug='calculadora-sueno'; whatIs='El sueño está compuesto de ciclos que duran aproximadamente 90 minutos. Cada ciclo incluye diferentes fases: sueño ligero, sueño profundo y REM (donde sueñas). Despiertas naturalmente al terminar un ciclo completo. Despertarte en el medio de un ciclo puede dejarte cansado. Calcular cuándo termina tu próximo ciclo es clave para levantarse descansado.'; whyUse='Necesitas calcular el mejor tiempo para despertarte o acostarte para minimizar el cansancio. Si sabes a qué hora necesitas despertar, esta herramienta te dice cuándo deberías acostarte para terminar ciclos completos. Es especialmente útil si duermes poco y quieres maximizar la calidad de tu descanso con el tiempo disponible.'},
    @{slug='test-compatibilidad'; whatIs='Un test de compatibilidad de pareja calcula qué tan compatible eres con otra persona basándose en criterios como signos zodiacales, nombres, gustos similares y otras características. Aunque es principalmente una herramienta lúdica y para entretenimiento, muchas personas disfrutan explorar su compatibilidad de esta forma.'; whyUse='Necesitas un test de compatibilidad para entretenimiento, curiosidad personal, o simplemente pasar un buen rato explorando si eres compatible con alguien. Es una herramienta divertida para usar con amigos, parejas, o solo por curiosidad sobre qué dicen los números.'},
    @{slug='numeros-suerte'; whatIs='Los números de la suerte son números que supuestamente te traen buena fortuna según la numerología, astrología u otras creencias culturales. Diferentes culturas tienen diferentes métodos para calcular números de la suerte basados en tu fecha de nacimiento o nombre. Aunque no tiene base científica, muchas personas disfrutan usando sus números de la suerte.'; whyUse='Necesitas números de la suerte para juegos de lotería, actividades de azar, o simplemente por diversión. Esta herramienta genera números basados en numerología o métodos de cálculo específicos. Es una herramienta de entretenimiento que muchas personas usan antes de comprar boletos de lotería o jugar juegos de azar.'},
    @{slug='numero-numerologia'; whatIs='La numerología es una creencia de que los números tienen significados místicos y pueden revelar aspectos de tu personalidad y destino. Tu número de vida se calcula a partir de tu fecha de nacimiento. Aunque no está científicamente probado, la numerología es una práctica cultural fascinante que muchas personas encuentran interesante e inspiradora.'; whyUse='Te interesa la numerología como herramienta de autoconocimiento, curiosidad espiritual, o entretenimiento. Esta calculadora te muestra tu número de vida y su significado numerológico. Muchas personas la usan como punto de reflexión personal o para explorar una perspectiva alternativa sobre ellos mismos.'},
)

# Generar archivo con las instrucciones
$output = "# INSTRUCCIONES PARA COMPLETAR TODO EL SEO

El siguiente PowerShell script debe correr en cada página .astro para agregar whatIs y whyUse.

## Datos a agregar por página:`n`n"

foreach ($calc in $calculadoras) {
    $output += "### $($calc.slug)`n"
    $output += "whatIs: `"$($calc.whatIs)`"`n"
    $output += "whyUse: `"$($calc.whyUse)`"`n`n"
}

$output | Out-File 'c:\Users\Jose\calzix\SEO_COMPLETO_DATOS.txt' -Encoding UTF8
Write-Host "✓ Archivo SEO_COMPLETO_DATOS.txt creado con todos los datos"
Write-Host "Total calculadoras con SEO generado: $($calculadoras.Count)"
