export type CalcDomain =
  // Matemáticas
  | 'matematicas-basicas'
  | 'algebra'
  | 'geometria'
  | 'estadistica'
  | 'trigonometria'
  | 'probabilidad'
  // Ciencias
  | 'fisica'
  | 'quimica'
  // Conversión
  | 'longitud'
  | 'peso'
  | 'temperatura'
  | 'velocidad'
  | 'area'
  | 'volumen'
  | 'energia'
  | 'presion'
  | 'tiempo'
  | 'datos'
  | 'angulos'
  | 'monedas'
  // Hogar
  | 'construccion'
  | 'pintura'
  | 'electricidad'
  | 'hipoteca'
  | 'consumo'
  | 'jardin'
  // Trabajo
  | 'facturacion'
  | 'descuentos'
  | 'nomina'
  | 'productividad'
  | 'propinas'
  // Educación
  | 'notas'
  | 'becas'
  | 'estudio'
  | 'lectura'
  // Viaje
  | 'combustible'
  | 'distancia'
  | 'zonas'
  | 'equipaje'
  | 'coste-viaje'
  // Naturaleza
  | 'carbono'
  | 'agua'
  | 'solar'
  | 'reciclaje'
  // Ocio
  | 'amor'
  | 'suerte'
  | 'numerologia'
  | 'sueno';

export interface CalcMeta {
  slug: string;
  name: string;
  description: string;
  longDescription: string;
  category: string;
  domain: CalcDomain;
  icon: string; // nombre del icono Lucide
  related: string[];
}

export interface DomainMeta { id: CalcDomain; label: string }
export interface GroupMeta {
  id: string;
  slug: string;
  label: string;
  description: string;
  domains: DomainMeta[];
}

export const CALC_GROUPS: GroupMeta[] = [
  {
    id: 'matematicas', slug: 'matematicas', label: 'Matemáticas',
    description: 'Calculadoras de aritmética, álgebra, geometría, estadística, trigonometría y probabilidad.',
    domains: [
      { id: 'matematicas-basicas', label: 'Básicas' },
      { id: 'algebra',             label: 'Álgebra' },
      { id: 'geometria',           label: 'Geometría' },
      { id: 'estadistica',         label: 'Estadística' },
      { id: 'trigonometria',       label: 'Trigonometría' },
      { id: 'probabilidad',        label: 'Probabilidad' },
    ],
  },
  {
    id: 'ciencias', slug: 'ciencias', label: 'Ciencias',
    description: 'Calculadoras de física y química para estudiantes y profesionales.',
    domains: [
      { id: 'fisica',  label: 'Física' },
      { id: 'quimica', label: 'Química' },
    ],
  },
  {
    id: 'conversion', slug: 'conversion', label: 'Conversión',
    description: 'Convierte entre todas las unidades del sistema métrico e imperial: longitud, peso, temperatura, velocidad y más.',
    domains: [
      { id: 'longitud',    label: 'Longitud y distancia' },
      { id: 'peso',        label: 'Peso y masa' },
      { id: 'temperatura', label: 'Temperatura' },
      { id: 'velocidad',   label: 'Velocidad' },
      { id: 'area',        label: 'Área y superficie' },
      { id: 'volumen',     label: 'Volumen y capacidad' },
      { id: 'energia',     label: 'Energía y potencia' },
      { id: 'presion',     label: 'Presión' },
      { id: 'tiempo',      label: 'Tiempo y duración' },
      { id: 'datos',       label: 'Datos digitales' },
      { id: 'angulos',     label: 'Ángulos' },
      { id: 'monedas',     label: 'Monedas' },
    ],
  },
  {
    id: 'hogar', slug: 'hogar', label: 'Hogar',
    description: 'Calculadoras para construcción, pintura, electricidad, hipotecas y eficiencia energética del hogar.',
    domains: [
      { id: 'construccion', label: 'Construcción' },
      { id: 'pintura',      label: 'Pintura y superficies' },
      { id: 'electricidad', label: 'Electricidad del hogar' },
      { id: 'hipoteca',     label: 'Hipoteca y alquiler' },
      { id: 'consumo',      label: 'Consumo energético' },
      { id: 'jardin',       label: 'Jardín y terreno' },
    ],
  },
  {
    id: 'trabajo', slug: 'trabajo', label: 'Trabajo',
    description: 'Calculadoras de facturación, IVA, descuentos, nóminas, productividad y propinas.',
    domains: [
      { id: 'facturacion',   label: 'Facturación e IVA' },
      { id: 'descuentos',    label: 'Descuentos y márgenes' },
      { id: 'nomina',        label: 'Nómina y salario' },
      { id: 'productividad', label: 'Productividad' },
      { id: 'propinas',      label: 'Propinas y cuenta' },
    ],
  },
  {
    id: 'educacion', slug: 'educacion', label: 'Educación',
    description: 'Calculadoras de notas, becas, planificación de estudio y velocidad de lectura.',
    domains: [
      { id: 'notas',   label: 'Notas y promedios' },
      { id: 'becas',   label: 'Becas y financiamiento' },
      { id: 'estudio', label: 'Tiempo de estudio' },
      { id: 'lectura', label: 'Lectura y velocidad' },
    ],
  },
  {
    id: 'viaje', slug: 'viaje', label: 'Viaje',
    description: 'Calculadoras de combustible, distancia, zonas horarias, equipaje y coste de viaje.',
    domains: [
      { id: 'combustible', label: 'Combustible y ruta' },
      { id: 'distancia',   label: 'Distancia y ruta' },
      { id: 'zonas',       label: 'Zonas horarias' },
      { id: 'equipaje',    label: 'Equipaje y peso' },
      { id: 'coste-viaje', label: 'Coste de viaje' },
    ],
  },
  {
    id: 'naturaleza', slug: 'naturaleza', label: 'Naturaleza',
    description: 'Calculadoras de huella de carbono, consumo de agua, energía solar y reciclaje.',
    domains: [
      { id: 'carbono',   label: 'Huella de carbono' },
      { id: 'agua',      label: 'Consumo de agua' },
      { id: 'solar',     label: 'Energía solar' },
      { id: 'reciclaje', label: 'Reciclaje' },
    ],
  },
  {
    id: 'ocio', slug: 'ocio', label: 'Ocio',
    description: 'Calculadoras lúdicas de compatibilidad, números de la suerte, numerología y sueño.',
    domains: [
      { id: 'amor',        label: 'Amor y compatibilidad' },
      { id: 'suerte',      label: 'Suerte y probabilidad' },
      { id: 'numerologia', label: 'Numerología' },
      { id: 'sueno',       label: 'Sueño y descanso' },
    ],
  },
];

export function getGroupBySlug(slug: string): GroupMeta | undefined {
  return CALC_GROUPS.find((g) => g.slug === slug);
}

export function getDomainGroup(domain: CalcDomain): GroupMeta | undefined {
  return CALC_GROUPS.find((g) => g.domains.some((d) => d.id === domain));
}

// Registro de calculadoras — añadir una entrada por herramienta nueva
export const CALCS: CalcMeta[] = [
  // ── Matemáticas ──────────────────────────────────────────────────────────
  {
    slug: 'calculadora-porcentaje',
    name: 'Calculadora de Porcentaje',
    description: 'Calcula porcentajes, variaciones y proporciones al instante.',
    longDescription: 'Obtén el porcentaje de una cantidad, calcula qué porcentaje representa un número sobre otro o halla el valor original a partir de un porcentaje dado.',
    category: 'Matemáticas básicas',
    domain: 'matematicas-basicas',
    icon: 'Percent',
    related: ['calculadora-descuento', 'calculadora-iva', 'nota-media'],
  },
  {
    slug: 'ecuacion-lineal',
    name: 'Ecuación Lineal',
    description: 'Resuelve ecuaciones de primer grado ax + b = 0.',
    longDescription: 'Introduce los coeficientes de tu ecuación lineal y obtén el valor de x en un solo paso, con los pasos de resolución explicados.',
    category: 'Álgebra',
    domain: 'algebra',
    icon: 'SquareFunction',
    related: ['calculadora-porcentaje', 'seno-coseno', 'probabilidad-simple'],
  },
  {
    slug: 'area-figuras',
    name: 'Área de Figuras',
    description: 'Calcula el área de círculos, triángulos, rectángulos y más.',
    longDescription: 'Selecciona la figura geométrica e introduce sus medidas para obtener el área y el perímetro de forma inmediata.',
    category: 'Geometría',
    domain: 'geometria',
    icon: 'Triangle',
    related: ['conversor-area', 'area-jardin', 'calculadora-pintura'],
  },
  {
    slug: 'media-mediana-moda',
    name: 'Media, Mediana y Moda',
    description: 'Obtén las medidas de tendencia central de tu conjunto de datos.',
    longDescription: 'Introduce una lista de números separados por comas y calcula automáticamente la media aritmética, la mediana y la moda.',
    category: 'Estadística',
    domain: 'estadistica',
    icon: 'BarChart2',
    related: ['probabilidad-simple', 'calculadora-porcentaje', 'nota-media'],
  },
  {
    slug: 'seno-coseno',
    name: 'Seno, Coseno y Tangente',
    description: 'Calcula las razones trigonométricas de cualquier ángulo.',
    longDescription: 'Introduce un ángulo en grados o radianes y obtén al instante su seno, coseno, tangente y las razones inversas.',
    category: 'Trigonometría',
    domain: 'trigonometria',
    icon: 'Sigma',
    related: ['conversor-angulos', 'area-figuras', 'ecuacion-lineal'],
  },
  {
    slug: 'probabilidad-simple',
    name: 'Probabilidad Simple',
    description: 'Calcula la probabilidad de un evento favorable sobre el total.',
    longDescription: 'Introduce el número de casos favorables y el total posible para obtener la probabilidad como fracción, decimal y porcentaje.',
    category: 'Probabilidad',
    domain: 'probabilidad',
    icon: 'Shuffle',
    related: ['media-mediana-moda', 'numeros-suerte', 'ecuacion-lineal'],
  },
  // ── Ciencias ─────────────────────────────────────────────────────────────
  {
    slug: 'velocidad-distancia-tiempo',
    name: 'Velocidad, Distancia y Tiempo',
    description: 'Despeja cualquier variable de la fórmula v = d / t.',
    longDescription: 'Introduce dos de las tres variables —velocidad, distancia o tiempo— y la calculadora despeja automáticamente la tercera.',
    category: 'Física',
    domain: 'fisica',
    icon: 'Zap',
    related: ['calculadora-distancia', 'consumo-combustible', 'conversor-velocidad'],
  },
  {
    slug: 'concentracion-molar',
    name: 'Concentración Molar',
    description: 'Calcula molaridad, moles y volumen de disoluciones.',
    longDescription: 'Introduce la masa del soluto, su masa molar y el volumen de la disolución para obtener la concentración molar en mol/L.',
    category: 'Química',
    domain: 'quimica',
    icon: 'FlaskConical',
    related: ['velocidad-distancia-tiempo', 'conversor-volumen', 'conversor-peso'],
  },
  // ── Conversión ───────────────────────────────────────────────────────────
  {
    slug: 'conversor-longitud',
    name: 'Conversor de Longitud',
    description: 'Convierte metros, kilómetros, millas, pies, pulgadas y más.',
    longDescription: 'Convierte al instante entre todas las unidades de longitud del sistema métrico e imperial: metros, kilómetros, centímetros, millas, yardas, pies y pulgadas.',
    category: 'Longitud y distancia',
    domain: 'longitud',
    icon: 'Ruler',
    related: ['conversor-peso', 'conversor-velocidad', 'calculadora-distancia'],
  },
  {
    slug: 'conversor-peso',
    name: 'Conversor de Peso',
    description: 'Convierte kilos, libras, onzas, gramos y toneladas.',
    longDescription: 'Transforma al instante entre unidades de peso y masa: kilogramos, gramos, miligramos, libras, onzas y toneladas métricas.',
    category: 'Peso y masa',
    domain: 'peso',
    icon: 'Weight',
    related: ['conversor-longitud', 'peso-equipaje', 'concentracion-molar'],
  },
  {
    slug: 'conversor-temperatura',
    name: 'Conversor de Temperatura',
    description: 'Convierte entre Celsius, Fahrenheit y Kelvin.',
    longDescription: 'Introduce cualquier temperatura en Celsius, Fahrenheit o Kelvin y obtén al instante la equivalencia en las otras dos escalas.',
    category: 'Temperatura',
    domain: 'temperatura',
    icon: 'Thermometer',
    related: ['conversor-longitud', 'conversor-velocidad', 'ahorro-energetico'],
  },
  {
    slug: 'conversor-velocidad',
    name: 'Conversor de Velocidad',
    description: 'Convierte km/h, m/s, mph, nudos y más.',
    longDescription: 'Transforma al instante entre unidades de velocidad: kilómetros por hora, metros por segundo, millas por hora, nudos y pies por segundo.',
    category: 'Velocidad',
    domain: 'velocidad',
    icon: 'Gauge',
    related: ['velocidad-distancia-tiempo', 'conversor-longitud', 'consumo-combustible'],
  },
  {
    slug: 'conversor-area',
    name: 'Conversor de Área',
    description: 'Convierte m², hectáreas, km², acres, pies² y más.',
    longDescription: 'Convierte entre unidades de superficie del sistema métrico e imperial: metros cuadrados, hectáreas, kilómetros cuadrados, acres y pies cuadrados.',
    category: 'Área y superficie',
    domain: 'area',
    icon: 'LayoutGrid',
    related: ['area-figuras', 'area-jardin', 'calculadora-pintura'],
  },
  {
    slug: 'conversor-volumen',
    name: 'Conversor de Volumen',
    description: 'Convierte litros, m³, galones, pinta, taza y más.',
    longDescription: 'Transforma al instante entre unidades de volumen y capacidad: litros, mililitros, metros cúbicos, galones, pintas y tazas.',
    category: 'Volumen y capacidad',
    domain: 'volumen',
    icon: 'Box',
    related: ['conversor-peso', 'concentracion-molar', 'consumo-agua'],
  },
  {
    slug: 'conversor-energia',
    name: 'Conversor de Energía',
    description: 'Convierte julios, calorías, kWh, BTU y más.',
    longDescription: 'Convierte entre unidades de energía y potencia: julios, kilojulios, calorías, kilocalorías, kilovatios hora y BTU.',
    category: 'Energía y potencia',
    domain: 'energia',
    icon: 'Battery',
    related: ['ahorro-energetico', 'ahorro-solar', 'consumo-electrico'],
  },
  {
    slug: 'conversor-presion',
    name: 'Conversor de Presión',
    description: 'Convierte pascales, bar, atm, psi y más.',
    longDescription: 'Transforma al instante entre unidades de presión: pascales, kilopascales, bar, atmósferas, milímetros de mercurio y PSI.',
    category: 'Presión',
    domain: 'presion',
    icon: 'Wind',
    related: ['velocidad-distancia-tiempo', 'conversor-temperatura', 'concentracion-molar'],
  },
  {
    slug: 'conversor-tiempo',
    name: 'Conversor de Tiempo',
    description: 'Convierte segundos, minutos, horas, días, semanas y años.',
    longDescription: 'Convierte al instante entre unidades de tiempo: segundos, minutos, horas, días, semanas, meses y años.',
    category: 'Tiempo y duración',
    domain: 'tiempo',
    icon: 'Clock',
    related: ['diferencia-horaria', 'tiempo-estudio', 'calculadora-productividad'],
  },
  {
    slug: 'conversor-datos',
    name: 'Conversor de Datos',
    description: 'Convierte bits, bytes, KB, MB, GB, TB y más.',
    longDescription: 'Transforma al instante entre unidades de almacenamiento digital: bits, bytes, kilobytes, megabytes, gigabytes y terabytes.',
    category: 'Datos digitales',
    domain: 'datos',
    icon: 'HardDrive',
    related: ['conversor-velocidad', 'calculadora-productividad'],
  },
  {
    slug: 'conversor-angulos',
    name: 'Conversor de Ángulos',
    description: 'Convierte grados, radianes, gradianes y vueltas.',
    longDescription: 'Convierte entre unidades angulares: grados sexagesimales, radianes, gradianes y vueltas completas.',
    category: 'Ángulos',
    domain: 'angulos',
    icon: 'Compass',
    related: ['seno-coseno', 'area-figuras', 'conversor-tiempo'],
  },
  {
    slug: 'conversor-monedas',
    name: 'Conversor de Monedas',
    description: 'Convierte entre las principales monedas del mundo.',
    longDescription: 'Introduce un importe y selecciona la moneda de origen y destino para obtener la conversión aproximada entre EUR, USD, GBP, JPY y más.',
    category: 'Monedas',
    domain: 'monedas',
    icon: 'DollarSign',
    related: ['calculadora-iva', 'calculadora-descuento', 'coste-viaje'],
  },
  // ── Hogar ────────────────────────────────────────────────────────────────
  {
    slug: 'materiales-construccion',
    name: 'Materiales de Construcción',
    description: 'Estima la cantidad de cemento, ladrillos o azulejos que necesitas.',
    longDescription: 'Introduce las dimensiones de tu proyecto y calcula automáticamente los materiales necesarios: cemento, arena, ladrillos o azulejos, con un margen de desperdicio incluido.',
    category: 'Construcción',
    domain: 'construccion',
    icon: 'Hammer',
    related: ['calculadora-pintura', 'area-jardin', 'conversor-area'],
  },
  {
    slug: 'calculadora-pintura',
    name: 'Calculadora de Pintura',
    description: 'Calcula los litros de pintura necesarios para tus paredes.',
    longDescription: 'Introduce las dimensiones de la habitación, descuenta puertas y ventanas, y obtén los litros de pintura necesarios con el rendimiento por litro.',
    category: 'Pintura y superficies',
    domain: 'pintura',
    icon: 'Paintbrush',
    related: ['materiales-construccion', 'conversor-area', 'area-figuras'],
  },
  {
    slug: 'consumo-electrico',
    name: 'Consumo Eléctrico',
    description: 'Calcula el coste eléctrico de tus electrodomésticos.',
    longDescription: 'Introduce la potencia en vatios, las horas de uso diarias y el precio del kWh para obtener el coste diario, mensual y anual de cualquier aparato.',
    category: 'Electricidad del hogar',
    domain: 'electricidad',
    icon: 'Zap',
    related: ['ahorro-energetico', 'ahorro-solar', 'conversor-energia'],
  },
  {
    slug: 'calculadora-hipoteca',
    name: 'Calculadora de Hipoteca',
    description: 'Calcula tu cuota mensual y el coste total de la hipoteca.',
    longDescription: 'Introduce el importe del préstamo, el tipo de interés anual y el plazo en años para obtener la cuota mensual, el total pagado y los intereses totales.',
    category: 'Hipoteca y alquiler',
    domain: 'hipoteca',
    icon: 'Home',
    related: ['calculadora-iva', 'calculadora-nomina', 'calculadora-beca'],
  },
  {
    slug: 'ahorro-energetico',
    name: 'Ahorro Energético',
    description: 'Compara el consumo de dos aparatos y calcula cuánto ahorras.',
    longDescription: 'Introduce la potencia y horas de uso de tu aparato actual frente al nuevo para calcular el ahorro energético anual y el tiempo de amortización.',
    category: 'Consumo energético',
    domain: 'consumo',
    icon: 'Leaf',
    related: ['consumo-electrico', 'ahorro-solar', 'conversor-energia'],
  },
  {
    slug: 'area-jardin',
    name: 'Área del Jardín',
    description: 'Calcula el área de tu jardín y estima el material necesario.',
    longDescription: 'Introduce las dimensiones de tu terreno para obtener el área total, y calcula la cantidad de césped, tierra o grava que necesitas.',
    category: 'Jardín y terreno',
    domain: 'jardin',
    icon: 'Sprout',
    related: ['materiales-construccion', 'conversor-area', 'calculadora-pintura'],
  },
  // ── Trabajo ──────────────────────────────────────────────────────────────
  {
    slug: 'calculadora-iva',
    name: 'Calculadora de IVA',
    description: 'Añade o extrae el IVA de cualquier importe al instante.',
    longDescription: 'Introduce el importe y el tipo de IVA para calcular el precio con IVA incluido, o extrae el IVA de un precio ya incluido.',
    category: 'Facturación e IVA',
    domain: 'facturacion',
    icon: 'Receipt',
    related: ['calculadora-descuento', 'calculadora-porcentaje', 'calculadora-nomina'],
  },
  {
    slug: 'calculadora-descuento',
    name: 'Calculadora de Descuentos',
    description: 'Calcula el precio final tras aplicar uno o varios descuentos.',
    longDescription: 'Introduce el precio original y el porcentaje de descuento para obtener el precio rebajado, el importe ahorrado y el margen comercial.',
    category: 'Descuentos y márgenes',
    domain: 'descuentos',
    icon: 'Tag',
    related: ['calculadora-iva', 'calculadora-porcentaje', 'calculadora-propina'],
  },
  {
    slug: 'calculadora-nomina',
    name: 'Calculadora de Nómina',
    description: 'Estima tu salario neto a partir del salario bruto anual.',
    longDescription: 'Introduce tu salario bruto anual, las retenciones de IRPF y las cotizaciones a la Seguridad Social para obtener una estimación del salario neto mensual.',
    category: 'Nómina y salario',
    domain: 'nomina',
    icon: 'Briefcase',
    related: ['calculadora-iva', 'calculadora-hipoteca', 'calculadora-productividad'],
  },
  {
    slug: 'calculadora-productividad',
    name: 'Productividad y Tiempo',
    description: 'Calcula tu tarifa horaria, rentabilidad y tiempo por tarea.',
    longDescription: 'Introduce tu salario objetivo y las horas trabajadas para obtener tu tarifa horaria ideal, o calcula cuánto vale tu tiempo en cada tarea.',
    category: 'Productividad',
    domain: 'productividad',
    icon: 'ListChecks',
    related: ['calculadora-nomina', 'tiempo-estudio', 'velocidad-lectura'],
  },
  {
    slug: 'calculadora-propina',
    name: 'Calculadora de Propina',
    description: 'Divide la cuenta y calcula la propina entre comensales.',
    longDescription: 'Introduce el importe total, el porcentaje de propina y el número de comensales para obtener cuánto debe pagar cada persona.',
    category: 'Propinas y cuenta',
    domain: 'propinas',
    icon: 'CreditCard',
    related: ['calculadora-descuento', 'calculadora-iva', 'coste-viaje'],
  },
  // ── Educación ────────────────────────────────────────────────────────────
  {
    slug: 'nota-media',
    name: 'Nota Media',
    description: 'Calcula tu nota media ponderada por créditos o porcentajes.',
    longDescription: 'Introduce tus notas y su peso o créditos para obtener la media ponderada, y calcula qué nota necesitas en el siguiente examen.',
    category: 'Notas y promedios',
    domain: 'notas',
    icon: 'GraduationCap',
    related: ['media-mediana-moda', 'calculadora-beca', 'tiempo-estudio'],
  },
  {
    slug: 'calculadora-beca',
    name: 'Calculadora de Beca',
    description: 'Estima si cumples los requisitos de renta para una beca.',
    longDescription: 'Introduce los ingresos familiares y el número de miembros del hogar para estimar el umbral de renta y tu elegibilidad para becas estatales.',
    category: 'Becas y financiamiento',
    domain: 'becas',
    icon: 'BookMarked',
    related: ['nota-media', 'calculadora-hipoteca', 'calculadora-nomina'],
  },
  {
    slug: 'tiempo-estudio',
    name: 'Tiempo de Estudio',
    description: 'Planifica cuántas horas necesitas estudiar para tu examen.',
    longDescription: 'Introduce el número de temas, las horas disponibles por día y los días hasta el examen para obtener un plan de estudio equilibrado.',
    category: 'Tiempo de estudio',
    domain: 'estudio',
    icon: 'Timer',
    related: ['nota-media', 'calculadora-productividad', 'velocidad-lectura'],
  },
  {
    slug: 'velocidad-lectura',
    name: 'Velocidad de Lectura',
    description: 'Mide tu velocidad lectora y estima cuánto tardas en un libro.',
    longDescription: 'Lee un texto de muestra durante un minuto, introduce las palabras leídas y obtén tu velocidad lectora en ppm y el tiempo estimado para cualquier libro.',
    category: 'Lectura y velocidad',
    domain: 'lectura',
    icon: 'BookOpen',
    related: ['tiempo-estudio', 'calculadora-productividad', 'nota-media'],
  },
  // ── Viaje ────────────────────────────────────────────────────────────────
  {
    slug: 'consumo-combustible',
    name: 'Consumo de Combustible',
    description: 'Calcula el gasto en gasolina o diésel de tu viaje.',
    longDescription: 'Introduce la distancia, el consumo del vehículo en L/100 km y el precio del combustible para obtener el coste total del trayecto.',
    category: 'Combustible y ruta',
    domain: 'combustible',
    icon: 'Car',
    related: ['calculadora-distancia', 'coste-viaje', 'huella-carbono'],
  },
  {
    slug: 'calculadora-distancia',
    name: 'Calculadora de Distancia',
    description: 'Convierte distancias y estima tiempos de viaje por velocidad.',
    longDescription: 'Introduce la distancia en kilómetros o millas y la velocidad media para calcular el tiempo de viaje, o convierte entre unidades de longitud.',
    category: 'Distancia y ruta',
    domain: 'distancia',
    icon: 'MapPin',
    related: ['consumo-combustible', 'conversor-longitud', 'velocidad-distancia-tiempo'],
  },
  {
    slug: 'diferencia-horaria',
    name: 'Diferencia Horaria',
    description: 'Calcula la diferencia horaria entre dos zonas del mundo.',
    longDescription: 'Selecciona dos zonas horarias y obtén la diferencia en horas, el horario equivalente y si se aplica el horario de verano.',
    category: 'Zonas horarias',
    domain: 'zonas',
    icon: 'Globe',
    related: ['conversor-tiempo', 'calculadora-distancia', 'coste-viaje'],
  },
  {
    slug: 'peso-equipaje',
    name: 'Calculadora de Equipaje',
    description: 'Comprueba si tu maleta cumple los límites de peso de la aerolínea.',
    longDescription: 'Introduce el peso de tu maleta, el límite de la aerolínea y el precio por kilo extra para saber si estás dentro del límite o cuánto te costará el exceso.',
    category: 'Equipaje y peso',
    domain: 'equipaje',
    icon: 'Package',
    related: ['conversor-peso', 'coste-viaje', 'calculadora-distancia'],
  },
  {
    slug: 'coste-viaje',
    name: 'Coste Total del Viaje',
    description: 'Suma todos los gastos de tu viaje y divídelos entre personas.',
    longDescription: 'Introduce los distintos gastos del viaje —vuelos, hotel, comida, transporte, actividades— y calcula el coste total y el coste por persona.',
    category: 'Coste de viaje',
    domain: 'coste-viaje',
    icon: 'Wallet',
    related: ['consumo-combustible', 'calculadora-propina', 'conversor-monedas'],
  },
  // ── Naturaleza ───────────────────────────────────────────────────────────
  {
    slug: 'huella-carbono',
    name: 'Huella de Carbono',
    description: 'Estima tu huella de CO₂ anual por transporte y hogar.',
    longDescription: 'Introduce tus hábitos de transporte y consumo energético doméstico para estimar tu huella de carbono anual en toneladas de CO₂ equivalente.',
    category: 'Huella de carbono',
    domain: 'carbono',
    icon: 'Leaf',
    related: ['consumo-electrico', 'ahorro-energetico', 'ahorro-solar'],
  },
  {
    slug: 'consumo-agua',
    name: 'Consumo de Agua',
    description: 'Calcula tu consumo diario de agua y su coste mensual.',
    longDescription: 'Introduce tus hábitos de consumo de agua —duchas, lavadora, lavavajillas, riego— para calcular el total de litros diarios y el coste mensual.',
    category: 'Consumo de agua',
    domain: 'agua',
    icon: 'Droplets',
    related: ['huella-carbono', 'ahorro-energetico', 'area-jardin'],
  },
  {
    slug: 'ahorro-solar',
    name: 'Ahorro con Paneles Solares',
    description: 'Estima el ahorro anual y el retorno de inversión de tu instalación solar.',
    longDescription: 'Introduce la potencia instalada, las horas de sol diarias y el precio del kWh para calcular la energía generada, el ahorro anual y los años de amortización.',
    category: 'Energía solar',
    domain: 'solar',
    icon: 'Sun',
    related: ['consumo-electrico', 'ahorro-energetico', 'conversor-energia'],
  },
  {
    slug: 'calculadora-reciclaje',
    name: 'Calculadora de Reciclaje',
    description: 'Calcula el impacto ambiental de tus residuos reciclados.',
    longDescription: 'Introduce los kilos de papel, plástico, vidrio y metal que reciclas al mes para estimar el CO₂ evitado, el agua ahorrada y los árboles equivalentes.',
    category: 'Reciclaje',
    domain: 'reciclaje',
    icon: 'Recycle',
    related: ['huella-carbono', 'consumo-agua', 'ahorro-energetico'],
  },
  // ── Ocio ─────────────────────────────────────────────────────────────────
  {
    slug: 'test-compatibilidad',
    name: 'Test de Compatibilidad',
    description: 'Descubre tu porcentaje de compatibilidad de pareja.',
    longDescription: 'Introduce los nombres de dos personas para obtener un índice de compatibilidad basado en un análisis lúdico de las letras y los números.',
    category: 'Amor y compatibilidad',
    domain: 'amor',
    icon: 'Heart',
    related: ['numeros-suerte', 'numero-numerologia', 'probabilidad-simple'],
  },
  {
    slug: 'numeros-suerte',
    name: 'Números de la Suerte',
    description: 'Genera tus números de la suerte personalizados.',
    longDescription: 'Obtén una combinación aleatoria de números de la suerte para lotería, primitiva o cualquier juego de azar, de forma completamente aleatoria.',
    category: 'Suerte y probabilidad',
    domain: 'suerte',
    icon: 'Star',
    related: ['probabilidad-simple', 'test-compatibilidad', 'numero-numerologia'],
  },
  {
    slug: 'numero-numerologia',
    name: 'Número de Numerología',
    description: 'Calcula tu número personal de la vida según la numerología.',
    longDescription: 'Introduce tu nombre completo o fecha de nacimiento para obtener tu número de la vida, número del destino y otros valores numerológicos.',
    category: 'Numerología',
    domain: 'numerologia',
    icon: 'Hash',
    related: ['test-compatibilidad', 'numeros-suerte', 'probabilidad-simple'],
  },
  {
    slug: 'calculadora-sueno',
    name: 'Calculadora de Sueño',
    description: 'Calcula la hora ideal para despertar según los ciclos de sueño.',
    longDescription: 'Introduce la hora a la que te vas a dormir y obtén las horas recomendadas para despertar de forma natural, respetando los ciclos de sueño de 90 minutos.',
    category: 'Sueño y descanso',
    domain: 'sueno',
    icon: 'Moon',
    related: ['tiempo-estudio', 'calculadora-productividad', 'test-compatibilidad'],
  },
  // ── Matemáticas (nuevas) ─────────────────────────────────────────────────
  // ── Ciencias (nuevas) ──────────────────────────────────────────────
  {
    slug: 'segunda-ley-newton',
    name: 'Segunda Ley de Newton',
    description: 'Calcula fuerzas, aceleración y masa usando F = m * a.',
    longDescription: 'Introduce dos de las tres variables (fuerza, masa, aceleración) y obtén la tercera.',
    category: 'Física',
    domain: 'fisica',
    icon: 'Zap',
    related: ['energia-cinetica', 'velocidad-distancia-tiempo', 'caida-libre'],
  },
  {
    slug: 'energia-cinetica',
    name: 'Energía Cinética',
    description: 'Calcula la energía cinética de un objeto en movimiento.',
    longDescription: 'Introduce masa y velocidad para obtener Ec = 1/2 * m * v².',
    category: 'Física',
    domain: 'fisica',
    icon: 'Zap',
    related: ['energia-potencial', 'segunda-ley-newton', 'velocidad-distancia-tiempo'],
  },
  {
    slug: 'energia-potencial',
    name: 'Energía Potencial',
    description: 'Calcula la energía potencial gravitatoria de un objeto.',
    longDescription: 'Introduce masa, gravedad y altura para Ep = m * g * h.',
    category: 'Física',
    domain: 'fisica',
    icon: 'Zap',
    related: ['energia-cinetica', 'segunda-ley-newton', 'caida-libre'],
  },
  {
    slug: 'ley-ohm',
    name: 'Ley de Ohm',
    description: 'Calcula voltaje, corriente o resistencia usando V = I * R.',
    longDescription: 'Introduce dos variables de V = I * R y obtén la tercera.',
    category: 'Física',
    domain: 'fisica',
    icon: 'Zap',
    related: ['potencia-electrica', 'consumo-electrico', 'cable-electrico'],
  },
  {
    slug: 'potencia-electrica',
    name: 'Potencia Eléctrica',
    description: 'Calcula la potencia eléctrica de un dispositivo.',
    longDescription: 'Introduce voltaje e intensidad para obtener la potencia en vatios.',
    category: 'Física',
    domain: 'fisica',
    icon: 'Zap',
    related: ['ley-ohm', 'consumo-electrico', 'conversor-energia'],
  },
  {
    slug: 'caida-libre',
    name: 'Caída Libre',
    description: 'Calcula tiempo, velocidad o altura en caída libre.',
    longDescription: 'Introduce dos variables de caída libre y obtén la tercera con gravedad 9.81 m/s².',
    category: 'Física',
    domain: 'fisica',
    icon: 'Zap',
    related: ['energia-potencial', 'segunda-ley-newton', 'velocidad-distancia-tiempo'],
  },
  {
    slug: 'presion-hidrostatica',
    name: 'Presión Hidrostática',
    description: 'Calcula la presión en un fluido a una profundidad dada.',
    longDescription: 'Introduce densidad, gravedad y profundidad para obtener presión hidrostática.',
    category: 'Física',
    domain: 'fisica',
    icon: 'Wind',
    related: ['conversor-presion', 'ley-ohm', 'consumo-agua'],
  },
  {
    slug: 'frecuencia-onda',
    name: 'Frecuencia de Onda',
    description: 'Calcula frecuencia, longitud de onda o velocidad.',
    longDescription: 'Introduce dos variables y obtén la tercera usando v = f * λ.',
    category: 'Física',
    domain: 'fisica',
    icon: 'Zap',
    related: ['velocidad-distancia-tiempo', 'conversor-velocidad', 'potencia-electrica'],
  },
  {
    slug: 'calor-especifico',
    name: 'Calor Específico',
    description: 'Calcula la energía necesaria para calentar una sustancia.',
    longDescription: 'Introduce masa, calor específico y cambio de temperatura.',
    category: 'Física',
    domain: 'fisica',
    icon: 'Zap',
    related: ['conversor-temperatura', 'conversor-energia', 'energia-potencial'],
  },
  {
    slug: 'calculadora-ph',
    name: 'Calculadora de pH',
    description: 'Calcula el pH a partir de la concentración de iones H⁺.',
    longDescription: 'Introduce la concentración molar de iones hidrógeno.',
    category: 'Química',
    domain: 'quimica',
    icon: 'FlaskConical',
    related: ['concentracion-molar', 'mol-masa-molar', 'gas-ideal'],
  },
  {
    slug: 'mol-masa-molar',
    name: 'Mol y Masa Molar',
    description: 'Calcula moles, masa y masa molar.',
    longDescription: 'Convierte entre moles y gramos usando masa molar.',
    category: 'Química',
    domain: 'quimica',
    icon: 'FlaskConical',
    related: ['concentracion-molar', 'calculadora-ph', 'gas-ideal'],
  },
  {
    slug: 'gas-ideal',
    name: 'Gas Ideal',
    description: 'Calcula propiedades usando la ley del gas ideal.',
    longDescription: 'Usa PV = nRT para resolver problemas de gases.',
    category: 'Química',
    domain: 'quimica',
    icon: 'FlaskConical',
    related: ['calculadora-ph', 'mol-masa-molar', 'diluciones-quimica'],
  },
  {
    slug: 'formula-molecular',
    name: 'Fórmula Molecular',
    description: 'Determina fórmula a partir de composición porcentual.',
    longDescription: 'Calcula proporciones atómicas en compuestos.',
    category: 'Química',
    domain: 'quimica',
    icon: 'FlaskConical',
    related: ['mol-masa-molar', 'estequiometria', 'numero-oxidacion'],
  },
  {
    slug: 'diluciones-quimica',
    name: 'Diluciones Química',
    description: 'Calcula concentración tras dilución.',
    longDescription: 'Usa M1V1 = M2V2 para disoluciones.',
    category: 'Química',
    domain: 'quimica',
    icon: 'FlaskConical',
    related: ['solucion-concentracion', 'calculadora-ph', 'concentracion-molar'],
  },
  {
    slug: 'estequiometria',
    name: 'Estequiometría',
    description: 'Calcula reactivos y productos en reacciones.',
    longDescription: 'Resuelve proporciones molares en reacciones químicas.',
    category: 'Química',
    domain: 'quimica',
    icon: 'FlaskConical',
    related: ['formula-molecular', 'mol-masa-molar', 'numero-oxidacion'],
  },
  {
    slug: 'solucion-concentracion',
    name: 'Solución y Concentración',
    description: 'Calcula concentración de disoluciones.',
    longDescription: 'Obtén molariedad, normalidad u otras unidades.',
    category: 'Química',
    domain: 'quimica',
    icon: 'FlaskConical',
    related: ['diluciones-quimica', 'calculadora-ph', 'concentracion-molar'],
  },
  {
    slug: 'equilibrio-quimico',
    name: 'Equilibrio Químico',
    description: 'Calcula constantes y concentraciones en equilibrio.',
    longDescription: 'Resuelve problemas de equilibrio químico.',
    category: 'Química',
    domain: 'quimica',
    icon: 'FlaskConical',
    related: ['solucion-concentracion', 'calculadora-ph', 'gas-ideal'],
  },
  {
    slug: 'numero-oxidacion',
    name: 'Número de Oxidación',
    description: 'Determina números de oxidación en compuestos.',
    longDescription: 'Asigna estados de oxidación a elementos.',
    category: 'Química',
    domain: 'quimica',
    icon: 'FlaskConical',
    related: ['formula-molecular', 'estequiometria', 'equilibrio-quimico'],
  },
  // ── Conversión (nuevas) ──────────────────────────────────────────────
  {
    slug: 'conversor-potencia',
    name: 'Conversor de Potencia',
    description: 'Convierte W, kW, HP, CV y más.',
    longDescription: 'Transforma entre unidades de potencia.',
    category: 'Energía y potencia',
    domain: 'energia',
    icon: 'Battery',
    related: ['conversor-energia', 'consumo-electrico', 'potencia-electrica'],
  },
  {
    slug: 'conversor-fuerza',
    name: 'Conversor de Fuerza',
    description: 'Convierte N, kN, dina, kgf y más.',
    longDescription: 'Transforma entre unidades de fuerza.',
    category: 'Presión',
    domain: 'presion',
    icon: 'Wind',
    related: ['conversor-presion', 'segunda-ley-newton', 'ley-ohm'],
  },
  {
    slug: 'conversor-densidad',
    name: 'Conversor de Densidad',
    description: 'Convierte kg/m³, g/cm³, lb/ft³.',
    longDescription: 'Transforma entre unidades de densidad.',
    category: 'Peso y masa',
    domain: 'peso',
    icon: 'Weight',
    related: ['conversor-peso', 'conversor-volumen', 'presion-hidrostatica'],
  },
  {
    slug: 'conversor-caudal',
    name: 'Conversor de Caudal',
    description: 'Convierte L/s, m³/h, ft³/s.',
    longDescription: 'Transforma entre unidades de flujo volumétrico.',
    category: 'Volumen y capacidad',
    domain: 'volumen',
    icon: 'Box',
    related: ['conversor-volumen', 'conversor-velocidad', 'presion-hidrostatica'],
  },
  {
    slug: 'conversor-par-motor',
    name: 'Conversor de Par Motor',
    description: 'Convierte N·m, kgf·m, lbf·ft.',
    longDescription: 'Transforma entre unidades de torque.',
    category: 'Presión',
    domain: 'presion',
    icon: 'Wind',
    related: ['conversor-fuerza', 'segunda-ley-newton', 'potencia-electrica'],
  },
  {
    slug: 'conversor-eficiencia',
    name: 'Conversor de Eficiencia',
    description: 'Convierte porcentaje, ratio, dB.',
    longDescription: 'Transforma entre escalas de eficiencia.',
    category: 'Velocidad',
    domain: 'velocidad',
    icon: 'Gauge',
    related: ['conversor-potencia', 'rentabilidad-roi', 'margen-beneficio'],
  },
  {
    slug: 'conversor-frecuencia',
    name: 'Conversor de Frecuencia',
    description: 'Convierte Hz, kHz, MHz, GHz.',
    longDescription: 'Transforma entre unidades de frecuencia.',
    category: 'Tiempo y duración',
    domain: 'tiempo',
    icon: 'Clock',
    related: ['conversor-tiempo', 'frecuencia-onda', 'velocidad-distancia-tiempo'],
  },
  {
    slug: 'conversor-iluminacion',
    name: 'Conversor de Iluminación',
    description: 'Convierte lux, fc, lm/m².',
    longDescription: 'Transforma entre unidades de luminancia.',
    category: 'Datos digitales',
    domain: 'datos',
    icon: 'HardDrive',
    related: ['conversor-energia', 'consumo-electrico', 'ahorro-energetico'],
  },
  {
    slug: 'calculadora-factorial',
    name: 'Calculadora de Factorial',
    description: 'Calcula el factorial de cualquier número entero.',
    longDescription: 'Introduce un número entero y obtén su factorial (n!), que es el producto de todos los enteros desde 1 hasta n.',
    category: 'Matemáticas básicas',
    domain: 'matematicas-basicas',
    icon: 'Calculator',
    related: ['permutaciones-combinaciones', 'numero-primo', 'mcm-mcd'],
  },
  {
    slug: 'potencias-raices',
    name: 'Potencias y Raíces',
    description: 'Calcula potencias, raíces cuadradas y cúbicas.',
    longDescription: 'Introduce la base y el exponente para calcular cualquier potencia, o calcula raíces cuadradas, cúbicas y de orden n de un número.',
    category: 'Matemáticas básicas',
    domain: 'matematicas-basicas',
    icon: 'Square',
    related: ['calculadora-factorial', 'numero-primo', 'ecuacion-lineal'],
  },
  {
    slug: 'mcm-mcd',
    name: 'MCM y MCD',
    description: 'Calcula el mínimo común múltiplo y el máximo común divisor.',
    longDescription: 'Introduce dos o más números y obtén el MCM (mínimo común múltiplo) y el MCD (máximo común divisor) al instante.',
    category: 'Matemáticas básicas',
    domain: 'matematicas-basicas',
    icon: 'Divide',
    related: ['numero-primo', 'permutaciones-combinaciones', 'calculadora-factorial'],
  },
  {
    slug: 'numero-primo',
    name: 'Verificador de Número Primo',
    description: 'Comprueba si un número es primo o compuesto.',
    longDescription: 'Introduce un número entero positivo y obtén si es primo, además de sus divisores si es compuesto.',
    category: 'Matemáticas básicas',
    domain: 'matematicas-basicas',
    icon: 'Hash',
    related: ['mcm-mcd', 'calculadora-factorial', 'media-mediana-moda'],
  },
  {
    slug: 'sistema-ecuaciones',
    name: 'Sistema de Ecuaciones Lineales',
    description: 'Resuelve sistemas de 2 o 3 ecuaciones lineales.',
    longDescription: 'Introduce los coeficientes de tu sistema de ecuaciones lineales (2x2 o 3x3) y obtén las soluciones de forma automática.',
    category: 'Álgebra',
    domain: 'algebra',
    icon: 'Grid3x3',
    related: ['ecuacion-lineal', 'funcion-cuadratica', 'seno-coseno'],
  },
  {
    slug: 'funcion-cuadratica',
    name: 'Función Cuadrática',
    description: 'Calcula raíces, vértice y propiedades de una parábola.',
    longDescription: 'Introduce los coeficientes a, b y c de una función cuadrática f(x)=ax²+bx+c y obtén las raíces, el vértice, el eje de simetría y más propiedades.',
    category: 'Álgebra',
    domain: 'algebra',
    icon: 'Parabola',
    related: ['sistema-ecuaciones', 'ecuacion-lineal', 'area-figuras'],
  },
  {
    slug: 'perimetro-figuras',
    name: 'Perímetro de Figuras',
    description: 'Calcula el perímetro de círculos, triángulos, rectángulos y más.',
    longDescription: 'Selecciona la figura geométrica, introduce sus dimensiones y obtén el perímetro de forma automática.',
    category: 'Geometría',
    domain: 'geometria',
    icon: 'Circle',
    related: ['area-figuras', 'volumen-solidos', 'teorema-pitagoras'],
  },
  {
    slug: 'volumen-solidos',
    name: 'Volumen de Sólidos',
    description: 'Calcula el volumen de esferas, cilindros, conos, cubos y más.',
    longDescription: 'Selecciona el sólido geométrico e introduce sus dimensiones para obtener el volumen automáticamente.',
    category: 'Geometría',
    domain: 'geometria',
    icon: 'Cube',
    related: ['perimetro-figuras', 'teorema-pitagoras', 'area-figuras'],
  },
  {
    slug: 'teorema-pitagoras',
    name: 'Teorema de Pitágoras',
    description: 'Calcula la hipotenusa o catetos de un triángulo rectángulo.',
    longDescription: 'Introduce dos lados de un triángulo rectángulo y obtén el tercero usando el teorema de Pitágoras (a² + b² = c²).',
    category: 'Geometría',
    domain: 'geometria',
    icon: 'Triangle',
    related: ['volumen-solidos', 'perimetro-figuras', 'seno-coseno'],
  },
  {
    slug: 'varianza-desviacion',
    name: 'Varianza y Desviación Típica',
    description: 'Calcula la varianza y la desviación estándar de tus datos.',
    longDescription: 'Introduce una serie de números separados por comas y obtén la varianza, la desviación estándar y otros indicadores de dispersión estadística.',
    category: 'Estadística',
    domain: 'estadistica',
    icon: 'TrendingUp',
    related: ['media-mediana-moda', 'correlacion-datos', 'distribucion-normal'],
  },
  {
    slug: 'correlacion-datos',
    name: 'Correlación de Datos',
    description: 'Calcula el coeficiente de correlación de Pearson entre dos variables.',
    longDescription: 'Introduce dos series de datos y obtén el coeficiente de correlación, que mide la relación lineal entre las variables.',
    category: 'Estadística',
    domain: 'estadistica',
    icon: 'LineChart',
    related: ['varianza-desviacion', 'media-mediana-moda', 'distribucion-normal'],
  },
  {
    slug: 'permutaciones-combinaciones',
    name: 'Permutaciones y Combinaciones',
    description: 'Calcula P(n,r) y C(n,r) para problemas de combinatoria.',
    longDescription: 'Introduce n y r para calcular permutaciones (importa el orden) y combinaciones (no importa el orden), también conocidas como variaciones.',
    category: 'Probabilidad',
    domain: 'probabilidad',
    icon: 'Layers',
    related: ['calculadora-factorial', 'probabilidad-simple', 'media-mediana-moda'],
  },
  {
    slug: 'distribucion-normal',
    name: 'Distribución Normal',
    description: 'Calcula probabilidades de la distribución normal estándar.',
    longDescription: 'Introduce el valor de z y obtén la probabilidad acumulada, la probabilidad entre dos valores y otros cálculos de la distribución normal.',
    category: 'Estadística',
    domain: 'estadistica',
    icon: 'Bell',
    related: ['varianza-desviacion', 'media-mediana-moda', 'probabilidad-simple'],
  },
  {
    slug: 'regla-tres',
    name: 'Calculadora de Regla de Tres',
    description: 'Resuelve reglas de tres simples y compuestas.',
    longDescription: 'Introduce tres valores conocidos en una proporción y obtén el valor desconocido usando la regla de tres.',
    category: 'Matemáticas básicas',
    domain: 'matematicas-basicas',
    icon: 'Ratio',
    related: ['calculadora-porcentaje', 'mcm-mcd', 'ecuacion-lineal'],
  },
  // ── Hogar (nuevas) ──────────────────────────────────────────────────
  { slug: 'presupuesto-obra', name: 'Presupuesto de Obra', description: 'Estima el coste total de proyectos de construcción.', longDescription: 'Calcula materiales, mano de obra y contingencias.', category: 'Construcción', domain: 'construccion', icon: 'Hammer', related: ['materiales-construccion', 'cemento-mortero', 'baldosas-suelo'] },
  { slug: 'cemento-mortero', name: 'Cemento y Mortero', description: 'Calcula cantidades de cemento y mortero.', longDescription: 'Estima materiales para construcción.', category: 'Construcción', domain: 'construccion', icon: 'Hammer', related: ['presupuesto-obra', 'materiales-construccion', 'conversor-densidad'] },
  { slug: 'baldosas-suelo', name: 'Baldosas de Suelo', description: 'Calcula el número de baldosas necesarias.', longDescription: 'Estima cobertura y desperdicio.', category: 'Construcción', domain: 'construccion', icon: 'Hammer', related: ['presupuesto-obra', 'conversor-area', 'materiales-construccion'] },
  { slug: 'pintura-techos', name: 'Pintura de Techos', description: 'Calcula la pintura necesaria para techos.', longDescription: 'Estima litros con rendimiento.', category: 'Pintura y superficies', domain: 'pintura', icon: 'Paintbrush', related: ['calculadora-pintura', 'pintura-exterior', 'materiales-construccion'] },
  { slug: 'pintura-exterior', name: 'Pintura Exterior', description: 'Calcula pintura para fachadas y exteriores.', longDescription: 'Estima cobertura con capas.', category: 'Pintura y superficies', domain: 'pintura', icon: 'Paintbrush', related: ['pintura-techos', 'calculadora-pintura', 'conversor-area'] },
  { slug: 'circuito-electrico', name: 'Circuito Eléctrico', description: 'Calcula parámetros de circuitos eléctricos.', longDescription: 'Resuelve tensión, intensidad, resistencia.', category: 'Electricidad del hogar', domain: 'electricidad', icon: 'Zap', related: ['ley-ohm', 'cable-electrico', 'potencia-electrica'] },
  { slug: 'cable-electrico', name: 'Cable Eléctrico', description: 'Calcula la sección de cable necesaria.', longDescription: 'Determina grosor según potencia y distancia.', category: 'Electricidad del hogar', domain: 'electricidad', icon: 'Zap', related: ['circuito-electrico', 'potencia-electrica', 'ley-ohm'] },
  { slug: 'instalacion-solar-hogar', name: 'Instalación Solar Hogar', description: 'Calcula sistema solar para vivienda.', longDescription: 'Estima potencia y número de paneles.', category: 'Electricidad del hogar', domain: 'electricidad', icon: 'Sun', related: ['ahorro-solar', 'potencia-electrica', 'consumo-electrico'] },
  { slug: 'amortizacion-hipoteca', name: 'Amortización Hipoteca', description: 'Calcula la cuota y amortización mensual.', longDescription: 'Desglose de capital e intereses.', category: 'Hipoteca y alquiler', domain: 'hipoteca', icon: 'Home', related: ['calculadora-hipoteca', 'alquiler-vs-compra', 'punto-equilibrio'] },
  { slug: 'alquiler-vs-compra', name: 'Alquiler vs Compra', description: 'Compara economía de alquilar versus comprar.', longDescription: 'Análisis financiero a largo plazo.', category: 'Hipoteca y alquiler', domain: 'hipoteca', icon: 'Home', related: ['amortizacion-hipoteca', 'calculadora-hipoteca', 'rentabilidad-roi'] },
  { slug: 'factura-gas', name: 'Factura de Gas', description: 'Calcula el coste de consumo de gas.', longDescription: 'Estima gasto mensual.', category: 'Consumo energético', domain: 'consumo', icon: 'Leaf', related: ['ahorro-energetico', 'consumo-electrico', 'conversor-energia'] },
  { slug: 'consumo-agua-hogar', name: 'Consumo Agua Hogar', description: 'Calcula el consumo diario de agua.', longDescription: 'Estima litros y coste mensual.', category: 'Consumo energético', domain: 'consumo', icon: 'Droplets', related: ['consumo-agua', 'ahorro-energetico', 'factura-gas'] },
  { slug: 'riego-jardin', name: 'Riego de Jardín', description: 'Calcula el sistema de riego óptimo.', longDescription: 'Estima tiempo y cantidad de agua.', category: 'Jardín y terreno', domain: 'jardin', icon: 'Sprout', related: ['area-jardin', 'consumo-agua-hogar', 'fertilizante-jardin'] },
  { slug: 'fertilizante-jardin', name: 'Fertilizante Jardín', description: 'Calcula la dosis de fertilizante.', longDescription: 'Estima cantidad según área.', category: 'Jardín y terreno', domain: 'jardin', icon: 'Sprout', related: ['riego-jardin', 'area-jardin', 'consumo-agua'] },
  // ── Trabajo (nuevas) ─────────────────────────────────────────────────
  { slug: 'precio-hora', name: 'Precio por Hora', description: 'Calcula tu tarifa horaria ideal.', longDescription: 'Estima precio según ingresos.', category: 'Facturación e IVA', domain: 'facturacion', icon: 'Receipt', related: ['margen-beneficio', 'punto-equilibrio', 'calculadora-iva'] },
  { slug: 'margen-beneficio', name: 'Margen de Beneficio', description: 'Calcula el margen y beneficio.', longDescription: 'Obtén margen bruto y neto.', category: 'Descuentos y márgenes', domain: 'descuentos', icon: 'TrendingUp', related: ['precio-hora', 'punto-equilibrio', 'rentabilidad-roi'] },
  { slug: 'punto-equilibrio', name: 'Punto de Equilibrio', description: 'Calcula el punto de equilibrio.', longDescription: 'Determina cantidad de venta.', category: 'Facturación e IVA', domain: 'facturacion', icon: 'BarChart2', related: ['margen-beneficio', 'rentabilidad-roi', 'precio-hora'] },
  { slug: 'rentabilidad-roi', name: 'Rentabilidad ROI', description: 'Calcula el retorno de inversión.', longDescription: 'Estima ROI en porcentaje.', category: 'Facturación e IVA', domain: 'facturacion', icon: 'PieChart', related: ['punto-equilibrio', 'margen-beneficio', 'alquiler-vs-compra'] },
  { slug: 'precio-coste-mas', name: 'Precio Coste+', description: 'Calcula precio con margen.', longDescription: 'Obtén precio final.', category: 'Descuentos y márgenes', domain: 'descuentos', icon: 'Tag', related: ['margen-beneficio', 'calculadora-iva', 'calculadora-descuento'] },
  { slug: 'descuento-volumen', name: 'Descuento por Volumen', description: 'Calcula descuentos escalonados.', longDescription: 'Estima descuento según cantidad.', category: 'Descuentos y márgenes', domain: 'descuentos', icon: 'Tag', related: ['calculadora-descuento', 'precio-coste-mas', 'calculadora-iva'] },
  { slug: 'precio-original-descuento', name: 'Precio Original Descuento', description: 'Halla el precio original con descuento.', longDescription: 'Calcula precio antes del descuento.', category: 'Descuentos y márgenes', domain: 'descuentos', icon: 'Tag', related: ['calculadora-descuento', 'calculadora-iva', 'precio-coste-mas'] },
  { slug: 'irpf-retencion', name: 'IRPF Retención', description: 'Calcula IRPF y retenciones.', longDescription: 'Estima retención fiscal.', category: 'Nómina y salario', domain: 'nomina', icon: 'Briefcase', related: ['calculadora-nomina', 'finiquito', 'vacaciones-proporcionales'] },
  { slug: 'finiquito', name: 'Finiquito', description: 'Calcula el finiquito de despido.', longDescription: 'Estima indemnización.', category: 'Nómina y salario', domain: 'nomina', icon: 'Briefcase', related: ['irpf-retencion', 'calculadora-nomina', 'vacaciones-proporcionales'] },
  { slug: 'vacaciones-proporcionales', name: 'Vacaciones Proporcionales', description: 'Calcula vacaciones por período.', longDescription: 'Estima días y coste.', category: 'Nómina y salario', domain: 'nomina', icon: 'Briefcase', related: ['finiquito', 'irpf-retencion', 'calculadora-nomina'] },
  { slug: 'horas-extra', name: 'Horas Extra', description: 'Calcula el coste de horas extra.', longDescription: 'Estima pago adicional.', category: 'Productividad', domain: 'productividad', icon: 'ListChecks', related: ['coste-reunion', 'pomodoro', 'calculadora-productividad'] },
  { slug: 'pomodoro', name: 'Técnica Pomodoro', description: 'Planifica sesiones de trabajo.', longDescription: 'Organiza tiempo en bloques.', category: 'Productividad', domain: 'productividad', icon: 'ListChecks', related: ['horas-extra', 'coste-reunion', 'tiempo-estudio'] },
  { slug: 'coste-reunion', name: 'Coste de Reunión', description: 'Calcula el coste de una reunión.', longDescription: 'Estima gasto según salario.', category: 'Productividad', domain: 'productividad', icon: 'ListChecks', related: ['horas-extra', 'pomodoro', 'precio-hora'] },
  { slug: 'propina-grupo', name: 'Propina Grupo', description: 'Divide la propina entre comensales.', longDescription: 'Calcula cuota por persona.', category: 'Propinas y cuenta', domain: 'propinas', icon: 'CreditCard', related: ['propina-porcentaje', 'calculadora-propina', 'calculadora-descuento'] },
  { slug: 'propina-porcentaje', name: 'Propina Porcentaje', description: 'Calcula la propina automática.', longDescription: 'Estima cantidad según porcentaje.', category: 'Propinas y cuenta', domain: 'propinas', icon: 'CreditCard', related: ['propina-grupo', 'calculadora-propina', 'calculadora-iva'] },
  // ── Educación (nuevas) ───────────────────────────────────────────────
  { slug: 'nota-necesaria', name: 'Nota Necesaria', description: 'Calcula la nota que necesitas.', longDescription: 'Determina qué nota necesitas.', category: 'Notas y promedios', domain: 'notas', icon: 'GraduationCap', related: ['nota-media', 'calculadora-beca', 'tiempo-estudio'] },
  { slug: 'nota-ponderada', name: 'Nota Ponderada', description: 'Calcula la media ponderada.', longDescription: 'Promedia notas con pesos.', category: 'Notas y promedios', domain: 'notas', icon: 'GraduationCap', related: ['nota-media', 'nota-necesaria', 'calculadora-beca'] },
  { slug: 'nota-selectividad', name: 'Nota Selectividad', description: 'Calcula nota de acceso.', longDescription: 'Combina notas para selectividad.', category: 'Notas y promedios', domain: 'notas', icon: 'GraduationCap', related: ['nota-ponderada', 'calculadora-beca', 'nota-media'] },
  { slug: 'conversion-notas', name: 'Conversión Notas', description: 'Convierte escalas de calificación.', longDescription: 'Transforma entre sistemas.', category: 'Notas y promedios', domain: 'notas', icon: 'GraduationCap', related: ['nota-media', 'nota-ponderada', 'nota-selectividad'] },
  { slug: 'simulador-beca', name: 'Simulador Beca', description: 'Simula elegibilidad de beca.', longDescription: 'Estima probabilidad.', category: 'Becas y financiamiento', domain: 'becas', icon: 'BookMarked', related: ['calculadora-beca', 'umbral-renta-beca', 'coste-carrera'] },
  { slug: 'umbral-renta-beca', name: 'Umbral Renta Beca', description: 'Calcula límite de renta.', longDescription: 'Determina si cumples requisitos.', category: 'Becas y financiamiento', domain: 'becas', icon: 'BookMarked', related: ['calculadora-beca', 'simulador-beca', 'coste-carrera'] },
  { slug: 'coste-carrera', name: 'Coste Carrera', description: 'Calcula inversión en estudios.', longDescription: 'Estima gasto total.', category: 'Becas y financiamiento', domain: 'becas', icon: 'BookMarked', related: ['umbral-renta-beca', 'simulador-beca', 'calculadora-beca'] },
  { slug: 'sesion-estudio', name: 'Sesión Estudio', description: 'Planifica sesión óptima.', longDescription: 'Organiza tiempo de estudio.', category: 'Tiempo de estudio', domain: 'estudio', icon: 'Timer', related: ['tiempo-estudio', 'aprendizaje-espaciado', 'pomodoro'] },
  { slug: 'aprendizaje-espaciado', name: 'Aprendizaje Espaciado', description: 'Planifica repaso espaciado.', longDescription: 'Organiza repasos efectivos.', category: 'Tiempo de estudio', domain: 'estudio', icon: 'Timer', related: ['sesion-estudio', 'tiempo-estudio', 'horas-idioma'] },
  { slug: 'horas-idioma', name: 'Horas Idioma', description: 'Calcula horas para idioma.', longDescription: 'Estima tiempo de aprendizaje.', category: 'Tiempo de estudio', domain: 'estudio', icon: 'Timer', related: ['aprendizaje-espaciado', 'sesion-estudio', 'plan-estudio'] },
  { slug: 'plan-estudio', name: 'Plan Estudio', description: 'Crea plan de estudios.', longDescription: 'Organiza calendario.', category: 'Tiempo de estudio', domain: 'estudio', icon: 'Timer', related: ['horas-idioma', 'aprendizaje-espaciado', 'tiempo-estudio'] },
  { slug: 'palabras-minuto', name: 'Palabras por Minuto', description: 'Mide velocidad lectora.', longDescription: 'Calcula WPM de lectura.', category: 'Lectura y velocidad', domain: 'lectura', icon: 'BookOpen', related: ['velocidad-lectura', 'tiempo-terminar-libro', 'libros-al-ano'] },
  { slug: 'tiempo-terminar-libro', name: 'Tiempo Terminar Libro', description: 'Estima tiempo de lectura.', longDescription: 'Calcula cuándo terminarás.', category: 'Lectura y velocidad', domain: 'lectura', icon: 'BookOpen', related: ['palabras-minuto', 'libros-al-ano', 'comprension-lectora'] },
  { slug: 'libros-al-ano', name: 'Libros al Año', description: 'Calcula libros anuales.', longDescription: 'Estima cantidad a leer.', category: 'Lectura y velocidad', domain: 'lectura', icon: 'BookOpen', related: ['tiempo-terminar-libro', 'palabras-minuto', 'paginas-por-dia'] },
  { slug: 'comprension-lectora', name: 'Comprensión Lectora', description: 'Evalúa comprensión de texto.', longDescription: 'Mide nivel de retención.', category: 'Lectura y velocidad', domain: 'lectura', icon: 'BookOpen', related: ['palabras-minuto', 'tiempo-terminar-libro', 'paginas-por-dia'] },
  { slug: 'paginas-por-dia', name: 'Páginas por Día', description: 'Planifica lectura diaria.', longDescription: 'Organiza progreso de lectura.', category: 'Lectura y velocidad', domain: 'lectura', icon: 'BookOpen', related: ['comprension-lectora', 'libros-al-ano', 'tiempo-terminar-libro'] },
  // ── Viaje (nuevas) ───────────────────────────────────────────────────
  { slug: 'autonomia-electrico', name: 'Autonomía Eléctrico', description: 'Calcula rango de batería.', longDescription: 'Estima km posibles con carga.', category: 'Combustible y ruta', domain: 'combustible', icon: 'Car', related: ['consumo-combustible', 'calculadora-distancia', 'coste-viaje'] },
  { slug: 'costo-gasolinera', name: 'Costo Gasolinera', description: 'Calcula coste de repostaje.', longDescription: 'Estima gasto en combustible.', category: 'Combustible y ruta', domain: 'combustible', icon: 'Car', related: ['autonomia-electrico', 'consumo-combustible', 'coste-viaje'] },
  { slug: 'litros-repostaje', name: 'Litros Repostaje', description: 'Calcula litros necesarios.', longDescription: 'Estima cantidad de repostaje.', category: 'Combustible y ruta', domain: 'combustible', icon: 'Car', related: ['costo-gasolinera', 'consumo-combustible', 'autonomia-electrico'] },
  { slug: 'distancia-a-pie', name: 'Distancia a Pie', description: 'Calcula tiempo de caminata.', longDescription: 'Estima duración de paseo.', category: 'Distancia y ruta', domain: 'distancia', icon: 'MapPin', related: ['distancia-ciclismo', 'ruta-senderismo', 'calculadora-distancia'] },
  { slug: 'distancia-ciclismo', name: 'Distancia Ciclismo', description: 'Calcula tiempo en bicicleta.', longDescription: 'Estima duración del recorrido.', category: 'Distancia y ruta', domain: 'distancia', icon: 'MapPin', related: ['distancia-a-pie', 'ruta-senderismo', 'calculadora-distancia'] },
  { slug: 'ruta-senderismo', name: 'Ruta Senderismo', description: 'Calcula tiempo de senderismo.', longDescription: 'Estima duración de excursión.', category: 'Distancia y ruta', domain: 'distancia', icon: 'MapPin', related: ['distancia-a-pie', 'distancia-ciclismo', 'calculadora-distancia'] },
  { slug: 'jet-lag', name: 'Jet Lag', description: 'Calcula efecto del desfase.', longDescription: 'Estima recuperación temporal.', category: 'Zonas horarias', domain: 'zonas', icon: 'Globe', related: ['diferencia-horaria', 'duracion-vuelo', 'coste-viaje'] },
  { slug: 'duracion-vuelo', name: 'Duración Vuelo', description: 'Calcula tiempo de vuelo.', longDescription: 'Estima duración estimada.', category: 'Zonas horarias', domain: 'zonas', icon: 'Globe', related: ['jet-lag', 'diferencia-horaria', 'exceso-equipaje'] },
  { slug: 'exceso-equipaje', name: 'Exceso Equipaje', description: 'Calcula coste exceso.', longDescription: 'Estima penalty de peso.', category: 'Equipaje y peso', domain: 'equipaje', icon: 'Package', related: ['dimensions-maleta', 'peso-equipaje', 'coste-viaje'] },
  { slug: 'dimensions-maleta', name: 'Dimensiones Maleta', description: 'Calcula volumen maleta.', longDescription: 'Verifica si entra en límite.', category: 'Equipaje y peso', domain: 'equipaje', icon: 'Package', related: ['exceso-equipaje', 'peso-equipaje', 'conversor-volumen'] },
  { slug: 'presupuesto-viaje', name: 'Presupuesto Viaje', description: 'Presupuesta gastos totales.', longDescription: 'Suma todos los gastos.', category: 'Coste de viaje', domain: 'coste-viaje', icon: 'Wallet', related: ['cambio-divisas', 'seguro-viaje', 'alojamiento-comparativa'] },
  { slug: 'cambio-divisas', name: 'Cambio Divisas', description: 'Convierte monedas.', longDescription: 'Obtén equivalencia actual.', category: 'Coste de viaje', domain: 'coste-viaje', icon: 'Wallet', related: ['presupuesto-viaje', 'conversor-monedas', 'coste-peajes'] },
  { slug: 'seguro-viaje', name: 'Seguro Viaje', description: 'Calcula coste seguro.', longDescription: 'Estima prima según duración.', category: 'Coste de viaje', domain: 'coste-viaje', icon: 'Wallet', related: ['presupuesto-viaje', 'alojamiento-comparativa', 'coste-peajes'] },
  { slug: 'alojamiento-comparativa', name: 'Alojamiento Comparativa', description: 'Compara costes alojamiento.', longDescription: 'Analiza opciones de hospedaje.', category: 'Coste de viaje', domain: 'coste-viaje', icon: 'Wallet', related: ['seguro-viaje', 'presupuesto-viaje', 'cambio-divisas'] },
  { slug: 'costo-peajes', name: 'Costo Peajes', description: 'Calcula coste de peajes.', longDescription: 'Estima gastos autopistas.', category: 'Coste de viaje', domain: 'coste-viaje', icon: 'Wallet', related: ['presupuesto-viaje', 'coste-viaje', 'cambio-divisas'] },
  // ── Naturaleza (nuevas) ───────────────────────────────────────────────
  { slug: 'co2-transporte', name: 'CO2 Transporte', description: 'Calcula emisiones de viaje.', longDescription: 'Estima CO2 por desplazamiento.', category: 'Huella de carbono', domain: 'carbono', icon: 'Leaf', related: ['huella-carbono', 'compensacion-co2', 'huella-alimentaria'] },
  { slug: 'compensacion-co2', name: 'Compensación CO2', description: 'Calcula offsets necesarios.', longDescription: 'Estima árboles a plantar.', category: 'Huella de carbono', domain: 'carbono', icon: 'Leaf', related: ['co2-transporte', 'huella-carbono', 'etiqueta-energetica'] },
  { slug: 'huella-alimentaria', name: 'Huella Alimentaria', description: 'Calcula impacto alimentos.', longDescription: 'Estima CO2 de dieta.', category: 'Huella de carbono', domain: 'carbono', icon: 'Leaf', related: ['co2-transporte', 'eficiencia-energetica', 'compensacion-co2'] },
  { slug: 'etiqueta-energetica', name: 'Etiqueta Energética', description: 'Calcula clase energética.', longDescription: 'Clasifica eficiencia.', category: 'Huella de carbono', domain: 'carbono', icon: 'Leaf', related: ['compensacion-co2', 'eficiencia-energetica', 'ahorro-energetico'] },
  { slug: 'consumo-ducha', name: 'Consumo Ducha', description: 'Calcula agua de ducha.', longDescription: 'Estima litros mensuales.', category: 'Consumo de agua', domain: 'agua', icon: 'Droplets', related: ['agua-alimentos', 'consumo-agua', 'captacion-lluvia'] },
  { slug: 'agua-alimentos', name: 'Agua Alimentos', description: 'Calcula agua en comida.', longDescription: 'Estima agua virtual.', category: 'Consumo de agua', domain: 'agua', icon: 'Droplets', related: ['consumo-ducha', 'huella-alimentaria', 'calidad-agua'] },
  { slug: 'calidad-agua', name: 'Calidad Agua', description: 'Evalúa pureza del agua.', longDescription: 'Determina nivel de contaminación.', category: 'Consumo de agua', domain: 'agua', icon: 'Droplets', related: ['agua-alimentos', 'consumo-ducha', 'captacion-lluvia'] },
  { slug: 'captacion-lluvia', name: 'Captación Lluvia', description: 'Calcula agua disponible.', longDescription: 'Estima litros recolectables.', category: 'Consumo de agua', domain: 'agua', icon: 'Droplets', related: ['calidad-agua', 'consumo-agua', 'riego-jardin'] },
  { slug: 'numero-placas-solar', name: 'Número Placas Solar', description: 'Calcula placas necesarias.', longDescription: 'Estima cantidad de paneles.', category: 'Energía solar', domain: 'solar', icon: 'Sun', related: ['angulo-solar', 'bateria-solar', 'ahorro-solar'] },
  { slug: 'angulo-solar', name: 'Ángulo Solar', description: 'Calcula ángulo óptimo.', longDescription: 'Determina inclinación ideal.', category: 'Energía solar', domain: 'solar', icon: 'Sun', related: ['numero-placas-solar', 'bateria-solar', 'conversor-angulos'] },
  { slug: 'bateria-solar', name: 'Batería Solar', description: 'Calcula capacidad batería.', longDescription: 'Estima almacenamiento energía.', category: 'Energía solar', domain: 'solar', icon: 'Sun', related: ['angulo-solar', 'numero-placas-solar', 'conversor-energia'] },
  { slug: 'plastico-reciclado', name: 'Plástico Reciclado', description: 'Calcula impacto reciclaje.', longDescription: 'Estima CO2 ahorrado.', category: 'Reciclaje', domain: 'reciclaje', icon: 'Recycle', related: ['papel-reciclado', 'residuos-electronicos', 'compost-organico'] },
  { slug: 'papel-reciclado', name: 'Papel Reciclado', description: 'Calcula ahorro papel.', longDescription: 'Estima árboles salvados.', category: 'Reciclaje', domain: 'reciclaje', icon: 'Recycle', related: ['plastico-reciclado', 'residuos-electronicos', 'compost-organico'] },
  { slug: 'residuos-electronicos', name: 'Residuos Electrónicos', description: 'Calcula impacto e-waste.', longDescription: 'Estima toxinas liberadas.', category: 'Reciclaje', domain: 'reciclaje', icon: 'Recycle', related: ['plastico-reciclado', 'papel-reciclado', 'compost-organico'] },
  { slug: 'compost-organico', name: 'Compost Orgánico', description: 'Calcula abono producido.', longDescription: 'Estima cantidad de compost.', category: 'Reciclaje', domain: 'reciclaje', icon: 'Recycle', related: ['residuos-electronicos', 'plastico-reciclado', 'fertilizante-jardin'] },
  { slug: 'eficiencia-energetica', name: 'Eficiencia Energética', description: 'Calcula eficiencia total.', longDescription: 'Evalúa ahorro potencial.', category: 'Huella de carbono', domain: 'carbono', icon: 'Leaf', related: ['etiqueta-energetica', 'ahorro-energetico', 'compensacion-co2'] },
  // ── Ocio (nuevas) ────────────────────────────────────────────────────
  { slug: 'compatibilidad-zodiacal', name: 'Compatibilidad Zodiacal', description: 'Calcula compatibilidad signos.', longDescription: 'Análisis astrológico lúdico.', category: 'Amor y compatibilidad', domain: 'amor', icon: 'Heart', related: ['test-compatibilidad', 'dias-juntos', 'nombre-amor'] },
  { slug: 'dias-juntos', name: 'Días Juntos', description: 'Calcula días de relación.', longDescription: 'Cuenta tiempo transcurrido.', category: 'Amor y compatibilidad', domain: 'amor', icon: 'Heart', related: ['compatibilidad-zodiacal', 'nombre-amor', 'presupuesto-boda'] },
  { slug: 'nombre-amor', name: 'Nombre Amor', description: 'Analiza compatibilidad nombres.', longDescription: 'Análisis lúdico de nombres.', category: 'Amor y compatibilidad', domain: 'amor', icon: 'Heart', related: ['dias-juntos', 'compatibilidad-zodiacal', 'presupuesto-boda'] },
  { slug: 'presupuesto-boda', name: 'Presupuesto Boda', description: 'Presupuesta gastos boda.', longDescription: 'Estima coste total.', category: 'Amor y compatibilidad', domain: 'amor', icon: 'Heart', related: ['nombre-amor', 'dias-juntos', 'coste-viaje'] },
  { slug: 'ruleta-decision', name: 'Ruleta Decisión', description: 'Elige al azar.', longDescription: 'Genera decisión aleatoria.', category: 'Suerte y probabilidad', domain: 'suerte', icon: 'Star', related: ['dado-virtual', 'cara-o-cruz', 'generador-loteria'] },
  { slug: 'dado-virtual', name: 'Dado Virtual', description: 'Simula tirada de dado.', longDescription: 'Genera número aleatorio.', category: 'Suerte y probabilidad', domain: 'suerte', icon: 'Star', related: ['ruleta-decision', 'cara-o-cruz', 'generador-loteria'] },
  { slug: 'cara-o-cruz', name: 'Cara o Cruz', description: 'Simula lanzamiento moneda.', longDescription: 'Genera cara o cruz.', category: 'Suerte y probabilidad', domain: 'suerte', icon: 'Star', related: ['dado-virtual', 'ruleta-decision', 'generador-loteria'] },
  { slug: 'generador-loteria', name: 'Generador Lotería', description: 'Genera números lotería.', longDescription: 'Crea combinación aleatoria.', category: 'Suerte y probabilidad', domain: 'suerte', icon: 'Star', related: ['cara-o-cruz', 'dado-virtual', 'numeros-suerte'] },
  { slug: 'camino-vida', name: 'Camino Vida', description: 'Calcula camino numerológico.', longDescription: 'Análisis numerológico.', category: 'Numerología', domain: 'numerologia', icon: 'Hash', related: ['numero-expresion', 'ciclos-personales', 'compatibilidad-numerologica'] },
  { slug: 'numero-expresion', name: 'Número Expresión', description: 'Calcula número expresión.', longDescription: 'Análisis del número personal.', category: 'Numerología', domain: 'numerologia', icon: 'Hash', related: ['camino-vida', 'ciclos-personales', 'numero-numerologia'] },
  { slug: 'ciclos-personales', name: 'Ciclos Personales', description: 'Calcula ciclos vitales.', longDescription: 'Determina períodos personales.', category: 'Numerología', domain: 'numerologia', icon: 'Hash', related: ['numero-expresion', 'camino-vida', 'compatibilidad-numerologica'] },
  { slug: 'compatibilidad-numerologica', name: 'Compatibilidad Numerológica', description: 'Calcula compatibilidad números.', longDescription: 'Análisis numerológico parejas.', category: 'Numerología', domain: 'numerologia', icon: 'Hash', related: ['ciclos-personales', 'numero-expresion', 'test-compatibilidad'] },
  { slug: 'ciclos-sueno', name: 'Ciclos Sueño', description: 'Calcula ciclos de sueño.', longDescription: 'Determina fases óptimas.', category: 'Sueño y descanso', domain: 'sueno', icon: 'Moon', related: ['deuda-sueno', 'hora-melatonina', 'siesta-optima'] },
  { slug: 'deuda-sueno', name: 'Deuda Sueño', description: 'Calcula falta de sueño.', longDescription: 'Estima privación acumulada.', category: 'Sueño y descanso', domain: 'sueno', icon: 'Moon', related: ['ciclos-sueno', 'hora-melatonina', 'calculadora-sueno'] },
  { slug: 'hora-melatonina', name: 'Hora Melatonina', description: 'Calcula pico melatonina.', longDescription: 'Determina mejor hora dormir.', category: 'Sueño y descanso', domain: 'sueno', icon: 'Moon', related: ['deuda-sueno', 'ciclos-sueno', 'siesta-optima'] },
  { slug: 'siesta-optima', name: 'Siesta Óptima', description: 'Calcula siesta ideal.', longDescription: 'Estima duración perfecta.', category: 'Sueño y descanso', domain: 'sueno', icon: 'Moon', related: ['hora-melatonina', 'ciclos-sueno', 'deuda-sueno'] },
  // ── Matemáticas (lote ampliación) ─────────────────────────────────────────
  { slug: 'calculadora-fracciones', name: 'Calculadora de Fracciones', description: 'Suma, resta, multiplica y divide fracciones y simplifica.', longDescription: 'Opera con dos fracciones y obtén el resultado simplificado y en decimal.', category: 'Matemáticas básicas', domain: 'matematicas-basicas', icon: 'Divide', related: ['calculadora-porcentaje', 'mcm-mcd', 'division-resto'] },
  { slug: 'numeros-romanos', name: 'Números Romanos', description: 'Convierte números a romanos y romanos a números.', longDescription: 'Conversor bidireccional de números arábigos y romanos del 1 al 3999.', category: 'Matemáticas básicas', domain: 'matematicas-basicas', icon: 'Hash', related: ['numero-expresion', 'redondeo', 'calculadora-factorial'] },
  { slug: 'raiz-cuadrada', name: 'Raíz Cuadrada y Enésima', description: 'Calcula raíces cuadradas, cúbicas y de cualquier índice.', longDescription: 'Obtén la raíz de cualquier índice e identifica si es exacta.', category: 'Matemáticas básicas', domain: 'matematicas-basicas', icon: 'Sigma', related: ['potencias-raices', 'teorema-pitagoras', 'logaritmo'] },
  { slug: 'redondeo', name: 'Calculadora de Redondeo', description: 'Redondea números al alza, a la baja o al más cercano.', longDescription: 'Redondea con los decimales que elijas en sus tres modos.', category: 'Matemáticas básicas', domain: 'matematicas-basicas', icon: 'Calculator', related: ['notacion-cientifica', 'calculadora-porcentaje', 'division-resto'] },
  { slug: 'notacion-cientifica', name: 'Notación Científica', description: 'Convierte números grandes o pequeños a notación científica.', longDescription: 'Expresa cualquier número como mantisa por potencia de diez.', category: 'Matemáticas básicas', domain: 'matematicas-basicas', icon: 'Calculator', related: ['redondeo', 'raiz-cuadrada', 'logaritmo'] },
  { slug: 'division-resto', name: 'División con Resto', description: 'Calcula cociente y resto de una división entera.', longDescription: 'Obtén cociente, resto y valor decimal de la división.', category: 'Matemáticas básicas', domain: 'matematicas-basicas', icon: 'Divide', related: ['calculadora-fracciones', 'mcm-mcd', 'numero-primo'] },
  { slug: 'logaritmo', name: 'Calculadora de Logaritmos', description: 'Calcula el logaritmo en cualquier base, ln y log decimal.', longDescription: 'Logaritmo en la base que elijas, natural y decimal.', category: 'Álgebra', domain: 'algebra', icon: 'SquareFunction', related: ['raiz-cuadrada', 'potencias-raices', 'progresiones'] },
  { slug: 'progresiones', name: 'Progresiones Aritmética y Geométrica', description: 'Calcula el término n y la suma de una progresión.', longDescription: 'Halla términos y sumas de progresiones aritméticas y geométricas.', category: 'Álgebra', domain: 'algebra', icon: 'Sigma', related: ['logaritmo', 'ecuacion-lineal', 'media-mediana-moda'] },
  { slug: 'distancia-dos-puntos', name: 'Distancia entre Dos Puntos', description: 'Calcula la distancia y el punto medio entre dos puntos.', longDescription: 'Distancia euclidiana y punto medio en el plano cartesiano.', category: 'Geometría', domain: 'geometria', icon: 'Triangle', related: ['teorema-pitagoras', 'area-figuras', 'perimetro-figuras'] },
  { slug: 'percentiles-cuartiles', name: 'Percentiles y Cuartiles', description: 'Calcula Q1, Q2, Q3, IQR y cualquier percentil.', longDescription: 'Obtén cuartiles, rango intercuartílico y percentiles de tus datos.', category: 'Estadística', domain: 'estadistica', icon: 'BarChart2', related: ['media-mediana-moda', 'varianza-desviacion', 'distribucion-normal'] },
  // ── Ciencias (lote ampliación) ────────────────────────────────────────────
  { slug: 'densidad', name: 'Densidad', description: 'Calcula densidad, masa o volumen con ρ = m/V.', longDescription: 'Despeja densidad, masa o volumen a partir de los otros dos.', category: 'Física', domain: 'fisica', icon: 'Scale', related: ['conversor-volumen', 'conversor-peso', 'presion-hidrostatica'] },
  { slug: 'trabajo-fisica', name: 'Trabajo Físico', description: 'Calcula el trabajo de una fuerza: W = F·d·cosθ.', longDescription: 'Obtén el trabajo en julios a partir de fuerza, distancia y ángulo.', category: 'Física', domain: 'fisica', icon: 'Zap', related: ['energia-cinetica', 'potencia-electrica', 'cantidad-movimiento'] },
  { slug: 'cantidad-movimiento', name: 'Cantidad de Movimiento', description: 'Calcula momento lineal, masa o velocidad (p = m·v).', longDescription: 'Despeja cantidad de movimiento, masa o velocidad.', category: 'Física', domain: 'fisica', icon: 'Zap', related: ['energia-cinetica', 'segunda-ley-newton', 'aceleracion'] },
  { slug: 'peso-masa', name: 'Peso y Masa', description: 'Calcula el peso (P = m·g) en distintos planetas.', longDescription: 'Convierte masa en peso según la gravedad del cuerpo celeste.', category: 'Física', domain: 'fisica', icon: 'Weight', related: ['segunda-ley-newton', 'caida-libre', 'conversor-peso'] },
  { slug: 'aceleracion', name: 'Aceleración', description: 'Calcula la aceleración a partir del cambio de velocidad.', longDescription: 'Obtén la aceleración con velocidad inicial, final y tiempo.', category: 'Física', domain: 'fisica', icon: 'Gauge', related: ['segunda-ley-newton', 'velocidad-distancia-tiempo', 'caida-libre'] },
  { slug: 'presion-fuerza-area', name: 'Presión (Fuerza/Área)', description: 'Calcula presión, fuerza o área con P = F/A.', longDescription: 'Despeja presión, fuerza o superficie de la presión mecánica.', category: 'Física', domain: 'fisica', icon: 'Wind', related: ['presion-hidrostatica', 'conversor-presion', 'densidad'] },
  { slug: 'ley-gases-combinada', name: 'Ley Combinada de los Gases', description: 'Relaciona P, V y T de un gas en dos estados.', longDescription: 'Resuelve P1V1/T1 = P2V2/T2 despejando la incógnita.', category: 'Química', domain: 'quimica', icon: 'FlaskConical', related: ['gas-ideal', 'concentracion-molar', 'numero-avogadro'] },
  { slug: 'numero-avogadro', name: 'Número de Avogadro', description: 'Convierte entre moles y número de partículas.', longDescription: 'Pasa de moles a partículas y viceversa con 6,022×10²³.', category: 'Química', domain: 'quimica', icon: 'FlaskConical', related: ['mol-masa-molar', 'concentracion-molar', 'estequiometria'] },
  { slug: 'rendimiento-reaccion', name: 'Rendimiento de Reacción', description: 'Calcula el rendimiento porcentual de una reacción.', longDescription: 'Obtén el % de rendimiento real frente al teórico.', category: 'Química', domain: 'quimica', icon: 'FlaskConical', related: ['estequiometria', 'mol-masa-molar', 'formula-molecular'] },
  { slug: 'concentracion-ppm', name: 'Concentración en ppm', description: 'Calcula partes por millón de una disolución.', longDescription: 'Obtén ppm y % en masa a partir de soluto y disolución.', category: 'Química', domain: 'quimica', icon: 'FlaskConical', related: ['concentracion-molar', 'diluciones-quimica', 'solucion-concentracion'] },
  // ── Conversión (lote ampliación) ──────────────────────────────────────────
  { slug: 'conversor-cocina', name: 'Conversor de Medidas de Cocina', description: 'Convierte tazas, cucharadas, ml, onzas y litros.', longDescription: 'Convierte entre las medidas de volumen de las recetas.', category: 'Volumen y capacidad', domain: 'volumen', icon: 'Box', related: ['conversor-volumen', 'conversor-peso'] },
  { slug: 'conversor-numeracion', name: 'Conversor de Bases Numéricas', description: 'Convierte binario, decimal, octal y hexadecimal.', longDescription: 'Pasa un número entre las cuatro bases de la informática.', category: 'Datos digitales', domain: 'datos', icon: 'HardDrive', related: ['conversor-datos', 'numeros-romanos'] },
  { slug: 'conversor-tiempo-decimal', name: 'Conversor de Tiempo Decimal', description: 'Convierte horas:minutos a horas decimales.', longDescription: 'Pasa de hh:mm a decimal y al revés para nóminas.', category: 'Tiempo y duración', domain: 'tiempo', icon: 'Clock', related: ['conversor-tiempo', 'horas-extra', 'precio-hora'] },
  { slug: 'conversor-coordenadas-gms', name: 'Conversor de Coordenadas GMS', description: 'Convierte grados decimales a grados/min/seg.', longDescription: 'Pasa coordenadas entre decimal y GMS en ambos sentidos.', category: 'Ángulos', domain: 'angulos', icon: 'Compass', related: ['conversor-angulos', 'calculadora-distancia'] },
  { slug: 'conversor-pendiente', name: 'Conversor de Pendiente', description: 'Convierte pendiente entre %, grados y proporción.', longDescription: 'Pasa la inclinación entre porcentaje, grados y 1:n.', category: 'Ángulos', domain: 'angulos', icon: 'Triangle', related: ['conversor-angulos', 'seno-coseno', 'ruta-senderismo'] },
  { slug: 'conversor-tallas-calzado', name: 'Conversor de Tallas de Calzado', description: 'Equivalencia de tallas EU, US y UK.', longDescription: 'Convierte tallas de zapatos entre sistemas y cm.', category: 'Longitud y distancia', domain: 'longitud', icon: 'Ruler', related: ['conversor-longitud'] },
  { slug: 'conversor-mah-wh', name: 'Conversor mAh a Wh', description: 'Convierte capacidad de baterías mAh ↔ Wh.', longDescription: 'Pasa de mAh a Wh con el voltaje de la batería.', category: 'Energía y potencia', domain: 'energia', icon: 'Battery', related: ['conversor-energia', 'consumo-electrico'] },
  { slug: 'conversor-escala-mapa', name: 'Conversor de Escala de Mapa', description: 'Calcula distancia real desde la escala del mapa.', longDescription: 'Convierte distancias entre mapa y realidad según la escala.', category: 'Longitud y distancia', domain: 'longitud', icon: 'MapPin', related: ['conversor-longitud', 'calculadora-distancia', 'conversor-area'] },
  { slug: 'conversor-viento', name: 'Escala de Viento (Beaufort)', description: 'Convierte km/h a grado Beaufort, nudos y m/s.', longDescription: 'Clasifica la velocidad del viento en la escala de Beaufort.', category: 'Velocidad', domain: 'velocidad', icon: 'Wind', related: ['conversor-velocidad'] },
  { slug: 'conversor-ritmo-velocidad', name: 'Conversor de Ritmo y Velocidad', description: 'Convierte ritmo (min/km) a velocidad (km/h).', longDescription: 'Pasa de ritmo de carrera a velocidad y viceversa.', category: 'Velocidad', domain: 'velocidad', icon: 'Gauge', related: ['conversor-velocidad', 'distancia-a-pie', 'distancia-ciclismo'] },
  // ── Hogar (lote ampliación) ───────────────────────────────────────────────
  { slug: 'hormigon-losa', name: 'Hormigón para Losa', description: 'Calcula el hormigón (m³) para una losa o solera.', longDescription: 'Estima el volumen de hormigón y los sacos de cemento.', category: 'Construcción', domain: 'construccion', icon: 'Hammer', related: ['materiales-construccion', 'cemento-mortero', 'presupuesto-obra'] },
  { slug: 'escalera-peldanos', name: 'Cálculo de Escalera', description: 'Calcula peldaños, huella y contrahuella.', longDescription: 'Diseña una escalera cómoda con la regla de Blondel.', category: 'Construcción', domain: 'construccion', icon: 'Hammer', related: ['materiales-construccion', 'baldosas-suelo', 'area-figuras'] },
  { slug: 'papel-pintado', name: 'Papel Pintado', description: 'Calcula los rollos de papel pintado necesarios.', longDescription: 'Estima rollos según perímetro, altura y medidas del rollo.', category: 'Pintura y superficies', domain: 'pintura', icon: 'Paintbrush', related: ['calculadora-pintura', 'pintura-techos', 'baldosas-suelo'] },
  { slug: 'potencia-contratada', name: 'Potencia a Contratar', description: 'Estima la potencia eléctrica a contratar (kW).', longDescription: 'Calcula la potencia óptima según tus aparatos.', category: 'Electricidad del hogar', domain: 'electricidad', icon: 'Zap', related: ['consumo-electrico', 'factura-gas', 'cable-electrico'] },
  { slug: 'ahorro-led', name: 'Ahorro al Cambiar a LED', description: 'Calcula cuánto ahorras cambiando a bombillas LED.', longDescription: 'Estima el ahorro anual al sustituir bombillas por LED.', category: 'Consumo energético', domain: 'consumo', icon: 'Leaf', related: ['consumo-electrico', 'ahorro-energetico', 'eficiencia-energetica'] },
  { slug: 'capacidad-endeudamiento', name: 'Capacidad de Endeudamiento', description: 'Calcula cuánto puedes pedir según tus ingresos.', longDescription: 'Estima tu cuota máxima y préstamo con la regla del 35%.', category: 'Hipoteca y alquiler', domain: 'hipoteca', icon: 'Home', related: ['calculadora-hipoteca', 'amortizacion-hipoteca', 'calculadora-nomina'] },
  { slug: 'gastos-compra-vivienda', name: 'Gastos de Compra de Vivienda', description: 'Calcula impuestos y gastos al comprar una casa.', longDescription: 'Estima los gastos de compraventa además del precio.', category: 'Hipoteca y alquiler', domain: 'hipoteca', icon: 'Receipt', related: ['calculadora-hipoteca', 'alquiler-vs-compra', 'capacidad-endeudamiento'] },
  { slug: 'consumo-climatizacion', name: 'Consumo de Climatización', description: 'Calcula el coste del aire o la calefacción.', longDescription: 'Estima el gasto eléctrico de climatización por temporada.', category: 'Consumo energético', domain: 'consumo', icon: 'Wind', related: ['consumo-electrico', 'ahorro-energetico', 'factura-gas'] },
  { slug: 'cesped-semillas', name: 'Semillas de Césped', description: 'Calcula los kilos de semilla para tu césped.', longDescription: 'Estima la semilla necesaria según superficie y dosis.', category: 'Jardín y terreno', domain: 'jardin', icon: 'Sprout', related: ['area-jardin', 'riego-jardin', 'fertilizante-jardin'] },
  { slug: 'piscina-volumen', name: 'Volumen de Piscina', description: 'Calcula los litros de agua de tu piscina.', longDescription: 'Obtén el volumen y la dosis de cloro de la piscina.', category: 'Jardín y terreno', domain: 'jardin', icon: 'Droplets', related: ['area-jardin', 'conversor-volumen', 'consumo-agua'] },
  // ── Trabajo (lote ampliación) ─────────────────────────────────────────────
  { slug: 'comision-ventas', name: 'Comisión de Ventas', description: 'Calcula la comisión de ventas y el total a cobrar.', longDescription: 'Obtén la comisión sobre ventas más el salario base.', category: 'Facturación e IVA', domain: 'facturacion', icon: 'TrendingUp', related: ['margen-beneficio', 'precio-hora', 'calculadora-iva'] },
  { slug: 'presupuesto-trabajo', name: 'Presupuesto de Trabajo', description: 'Calcula un presupuesto con materiales, mano de obra, margen e IVA.', longDescription: 'Elabora un presupuesto profesional con todos los conceptos.', category: 'Facturación e IVA', domain: 'facturacion', icon: 'Receipt', related: ['precio-hora', 'precio-coste-mas', 'calculadora-iva'] },
  { slug: 'recargo-mora', name: 'Intereses de Demora', description: 'Calcula el recargo por mora de una factura impagada.', longDescription: 'Obtén los intereses de demora por pago fuera de plazo.', category: 'Facturación e IVA', domain: 'facturacion', icon: 'Receipt', related: ['calculadora-iva', 'margen-beneficio', 'rentabilidad-roi'] },
  { slug: 'descuento-sucesivo', name: 'Descuentos Sucesivos', description: 'Encadena varios descuentos y halla el equivalente.', longDescription: 'Aplica descuentos sucesivos y el descuento único equivalente.', category: 'Descuentos y márgenes', domain: 'descuentos', icon: 'Tag', related: ['calculadora-descuento', 'precio-original-descuento', 'descuento-volumen'] },
  { slug: 'descuento-pronto-pago', name: 'Descuento por Pronto Pago', description: 'Calcula el ahorro por pagar una factura antes.', longDescription: 'Obtén el descuento por pronto pago y su rentabilidad.', category: 'Descuentos y márgenes', domain: 'descuentos', icon: 'Tag', related: ['calculadora-descuento', 'descuento-sucesivo', 'rentabilidad-roi'] },
  { slug: 'salario-por-hora', name: 'Salario por Hora', description: 'Convierte salario anual a por hora y viceversa.', longDescription: 'Pasa de salario anual a por hora según tu jornada.', category: 'Nómina y salario', domain: 'nomina', icon: 'Briefcase', related: ['calculadora-nomina', 'precio-hora', 'horas-extra'] },
  { slug: 'coste-empresa-trabajador', name: 'Coste de un Trabajador', description: 'Calcula el coste total de un empleado para la empresa.', longDescription: 'Estima el coste empresarial: bruto más cotizaciones.', category: 'Nómina y salario', domain: 'nomina', icon: 'Briefcase', related: ['calculadora-nomina', 'salario-por-hora', 'irpf-retencion'] },
  { slug: 'paga-extra', name: 'Pagas Extra', description: 'Reparte el salario anual entre 12, 14, 15 o 16 pagas.', longDescription: 'Calcula el importe de cada paga y el prorrateo.', category: 'Nómina y salario', domain: 'nomina', icon: 'Briefcase', related: ['calculadora-nomina', 'finiquito', 'salario-por-hora'] },
  { slug: 'objetivo-ventas', name: 'Objetivo de Ventas Diario', description: 'Reparte la meta mensual en un objetivo diario.', longDescription: 'Calcula cuánto vender al día para llegar a la meta.', category: 'Productividad', domain: 'productividad', icon: 'ListChecks', related: ['calculadora-productividad', 'comision-ventas', 'punto-equilibrio'] },
  { slug: 'reparto-propinas', name: 'Reparto de Propinas', description: 'Reparte las propinas del equipo por horas trabajadas.', longDescription: 'Distribuye propinas de forma proporcional a las horas.', category: 'Propinas y cuenta', domain: 'propinas', icon: 'CreditCard', related: ['calculadora-propina', 'propina-grupo', 'propina-porcentaje'] },
  // ── Educación (lote ampliación) ───────────────────────────────────────────
  { slug: 'nota-curva', name: 'Nota con Curva', description: 'Aplica una curva de calificación a tu nota.', longDescription: 'Ajusta tu nota con el método de curva lineal.', category: 'Notas y promedios', domain: 'notas', icon: 'GraduationCap', related: ['nota-media', 'nota-necesaria', 'conversion-notas'] },
  { slug: 'promedio-acumulado', name: 'Promedio Acumulado', description: 'Calcula tu GPA acumulado por créditos.', longDescription: 'Combina tu promedio anterior con el del nuevo periodo.', category: 'Notas y promedios', domain: 'notas', icon: 'GraduationCap', related: ['nota-media', 'nota-ponderada', 'nota-letra'] },
  { slug: 'nota-letra', name: 'Nota a Letra', description: 'Convierte una nota numérica en letra (A-F).', longDescription: 'Traduce tu nota a calificación por letras y etiqueta.', category: 'Notas y promedios', domain: 'notas', icon: 'GraduationCap', related: ['conversion-notas', 'nota-media', 'promedio-acumulado'] },
  { slug: 'prestamo-estudiantil', name: 'Préstamo Estudiantil', description: 'Calcula la cuota de un préstamo para estudios.', longDescription: 'Obtén cuota, total e intereses de un préstamo estudiantil.', category: 'Becas y financiamiento', domain: 'becas', icon: 'BookMarked', related: ['calculadora-beca', 'beca-cobertura', 'calculadora-hipoteca'] },
  { slug: 'beca-cobertura', name: 'Cobertura de Beca', description: 'Calcula qué porcentaje de los costes cubre tu beca.', longDescription: 'Obtén el % cubierto y lo que aportas de tu bolsillo.', category: 'Becas y financiamiento', domain: 'becas', icon: 'BookMarked', related: ['calculadora-beca', 'simulador-beca', 'prestamo-estudiantil'] },
  { slug: 'presupuesto-estudiante', name: 'Presupuesto de Estudiante', description: 'Calcula tus gastos mensuales como estudiante.', longDescription: 'Suma alojamiento, comida, transporte y más al mes.', category: 'Becas y financiamiento', domain: 'becas', icon: 'Wallet', related: ['beca-cobertura', 'prestamo-estudiantil', 'calculadora-beca'] },
  { slug: 'flashcards-repaso', name: 'Flashcards por Día', description: 'Reparte tus tarjetas de estudio entre los días.', longDescription: 'Planifica tu repaso con flashcards y repetición espaciada.', category: 'Tiempo de estudio', domain: 'estudio', icon: 'Timer', related: ['aprendizaje-espaciado', 'tiempo-estudio', 'plan-estudio'] },
  { slug: 'horas-ects', name: 'Créditos ECTS a Horas', description: 'Convierte créditos ECTS en horas de estudio.', longDescription: 'Calcula las horas de trabajo que suponen tus créditos.', category: 'Tiempo de estudio', domain: 'estudio', icon: 'Timer', related: ['tiempo-estudio', 'plan-estudio', 'sesion-estudio'] },
  { slug: 'tiempo-audiolibro', name: 'Duración de Audiolibro', description: 'Calcula cuánto dura un audiolibro.', longDescription: 'Estima las horas de audio según páginas y narración.', category: 'Lectura y velocidad', domain: 'lectura', icon: 'BookOpen', related: ['tiempo-terminar-libro', 'velocidad-lectura', 'palabras-libro'] },
  { slug: 'palabras-libro', name: 'Palabras de un Libro', description: 'Calcula cuántas palabras tiene un libro.', longDescription: 'Estima las palabras totales y el tiempo de lectura.', category: 'Lectura y velocidad', domain: 'lectura', icon: 'BookOpen', related: ['velocidad-lectura', 'tiempo-terminar-libro', 'tiempo-audiolibro'] },
];

export function getCalcsByDomain(domain: CalcDomain): CalcMeta[] {
  return CALCS.filter((c) => c.domain === domain);
}

export function getCalcBySlug(slug: string): CalcMeta | undefined {
  return CALCS.find((c) => c.slug === slug);
}

export function getRelatedCalcs(slug: string): CalcMeta[] {
  const calc = getCalcBySlug(slug);
  if (!calc) return [];
  return calc.related
    .map((s) => getCalcBySlug(s))
    .filter((c): c is CalcMeta => c !== undefined)
    .slice(0, 4);
}
